"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DescriptionAuthorship = exports.Source = exports.Gall = exports.Seed = exports.Fruit = exports.Ginoecium = exports.Pollen = exports.Androecium = exports.Flower = exports.Inflorescence = exports.Leaf = exports.Stipule = exports.Prickles = exports.Trichomes = exports.Stems = void 0;
var Stems_1 = require("./Stems");
Object.defineProperty(exports, "Stems", { enumerable: true, get: function () { return Stems_1.Stems; } });
var Trichomes_1 = require("./Trichomes");
Object.defineProperty(exports, "Trichomes", { enumerable: true, get: function () { return Trichomes_1.Trichomes; } });
var Prickles_1 = require("./Prickles");
Object.defineProperty(exports, "Prickles", { enumerable: true, get: function () { return Prickles_1.Prickles; } });
var Stipule_1 = require("./Stipule");
Object.defineProperty(exports, "Stipule", { enumerable: true, get: function () { return Stipule_1.Stipule; } });
var Leaf_1 = require("./Leaf");
Object.defineProperty(exports, "Leaf", { enumerable: true, get: function () { return Leaf_1.Leaf; } });
var Inflorescence_1 = require("./Inflorescence");
Object.defineProperty(exports, "Inflorescence", { enumerable: true, get: function () { return Inflorescence_1.Inflorescence; } });
var Flower_1 = require("./Flower");
Object.defineProperty(exports, "Flower", { enumerable: true, get: function () { return Flower_1.Flower; } });
var Androecium_1 = require("./Androecium");
Object.defineProperty(exports, "Androecium", { enumerable: true, get: function () { return Androecium_1.Androecium; } });
var Pollen_1 = require("./Pollen");
Object.defineProperty(exports, "Pollen", { enumerable: true, get: function () { return Pollen_1.Pollen; } });
var Ginoecium_1 = require("./Ginoecium");
Object.defineProperty(exports, "Ginoecium", { enumerable: true, get: function () { return Ginoecium_1.Ginoecium; } });
var Fruit_1 = require("./Fruit");
Object.defineProperty(exports, "Fruit", { enumerable: true, get: function () { return Fruit_1.Fruit; } });
var Seed_1 = require("./Seed");
Object.defineProperty(exports, "Seed", { enumerable: true, get: function () { return Seed_1.Seed; } });
var Gall_1 = require("./Gall");
Object.defineProperty(exports, "Gall", { enumerable: true, get: function () { return Gall_1.Gall; } });
var Source_1 = require("./Source");
Object.defineProperty(exports, "Source", { enumerable: true, get: function () { return Source_1.Source; } });
var descriptionAuthorship_1 = require("./descriptionAuthorship");
Object.defineProperty(exports, "DescriptionAuthorship", { enumerable: true, get: function () { return descriptionAuthorship_1.DescriptionAuthorship; } });
