"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_dryandroides_var_dryandroides = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Setiform_1 = require("../../characters/v1/Trichomes/Setiform");
var Stipule_1 = require("../../characters/v1/Stipule");
var Leaf_1 = require("../../characters/v1/Leaf");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Androecium_1 = require("../../characters/v1/Androecium");
var Ginoecium_1 = require("../../characters/v1/Ginoecium");
var Fruit_1 = require("../../characters/v1/Fruit");
// Import annotation classes
var v1_2 = require("../../characters/v1");
// Description of Mimosa dryandroides_var_dryandroides
var Mimosa_dryandroides_var_dryandroides = new _1.Mimosa();
exports.Mimosa_dryandroides_var_dryandroides = Mimosa_dryandroides_var_dryandroides;
Mimosa_dryandroides_var_dryandroides.specificEpithet = 'dryandroides var. dryandroides';
Mimosa_dryandroides_var_dryandroides.stems = new v1_1.Stems();
Mimosa_dryandroides_var_dryandroides.stems.trichomes = new v1_1.Trichomes();
Mimosa_dryandroides_var_dryandroides.stems.trichomes.setiform = new Trichomes_1.Setiform();
Mimosa_dryandroides_var_dryandroides.stems.trichomes.setiform.barbellate = new Setiform_1.SetiformBarbellate();
Mimosa_dryandroides_var_dryandroides.stems.trichomes.setiform.barbellate.are = 'present';
Mimosa_dryandroides_var_dryandroides.stems.trichomes.granular = new Trichomes_1.Granular();
Mimosa_dryandroides_var_dryandroides.stems.trichomes.granular.are = 'present';
Mimosa_dryandroides_var_dryandroides.stipule = new v1_1.Stipule();
Mimosa_dryandroides_var_dryandroides.stipule.margin = new Stipule_1.MarginStipule();
Mimosa_dryandroides_var_dryandroides.stipule.adaxial = new Stipule_1.AdaxialStipule();
Mimosa_dryandroides_var_dryandroides.stipule.abaxial = new Stipule_1.AbaxialStipule();
Mimosa_dryandroides_var_dryandroides.leaf = new v1_1.Leaf();
Mimosa_dryandroides_var_dryandroides.leaf.petiole = new Leaf_1.Petiole();
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate.pinnae = new Pinnae_1.Pinnae();
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate.pinnae.setNumberOfPairs(1);
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(20, 28);
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_dryandroides_var_dryandroides.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_dryandroides_var_dryandroides.inflorescence = new v1_1.Inflorescence();
Mimosa_dryandroides_var_dryandroides.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_dryandroides_var_dryandroides.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_dryandroides_var_dryandroides.flower = new Flower_1.Flower();
Mimosa_dryandroides_var_dryandroides.flower.bracteole = new Flower_1.Bracteole();
Mimosa_dryandroides_var_dryandroides.flower.merism = '4-merous';
Mimosa_dryandroides_var_dryandroides.flower.numberWhorlsOfStamens = 'isostemonous';
Mimosa_dryandroides_var_dryandroides.flower.calyx = new Flower_1.Calyx();
Mimosa_dryandroides_var_dryandroides.flower.calyx.shape = 'pappiform';
Mimosa_dryandroides_var_dryandroides.flower.corolla = new Flower_1.Corolla();
Mimosa_dryandroides_var_dryandroides.flower.corolla.shape = 'campanulate';
Mimosa_dryandroides_var_dryandroides.androecium = new v1_1.Androecium();
Mimosa_dryandroides_var_dryandroides.androecium.filaments = new Androecium_1.Filaments();
Mimosa_dryandroides_var_dryandroides.androecium.filaments.colour = 'pinkish';
Mimosa_dryandroides_var_dryandroides.ginoecium = new v1_1.Ginoecium();
Mimosa_dryandroides_var_dryandroides.ginoecium.ovary = new Ginoecium_1.Ovary();
Mimosa_dryandroides_var_dryandroides.fruit = new v1_1.Fruit();
Mimosa_dryandroides_var_dryandroides.fruit.stipe = new Fruit_1.Stipe();
Mimosa_dryandroides_var_dryandroides.fruit.replum = new Fruit_1.Replum();
Mimosa_dryandroides_var_dryandroides.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_dryandroides_var_dryandroides.seed = new v1_1.Seed();
// Description authorship
Mimosa_dryandroides_var_dryandroides.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_dryandroides_var_dryandroides.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source0 = new v1_2.Source();
source0.sourceType = 'article';
source0.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source0.year = 2018;
source0.title = 'Toward a Census of *Mimosa* (Leguminosae) in the Atlantic Domain, Southeastern Brazil';
source0.journal = 'Systematic Botany';
source0.volume = 43;
source0.number = 1;
source0.pages = 162 - 197;
Mimosa_dryandroides_var_dryandroides.addSource(source0);
/// Trichomes
var source1 = new v1_2.Source();
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source1.year = 2020;
source1.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source1.journal = 'Flora';
source1.number = 272;
source1.pages = 151702;
source1.figure = '3A';
source1.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_dryandroides_var_dryandroides.stems.trichomes.setiform.barbellate.addSource(source1);
var source2 = new v1_2.Source();
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source2.year = 2020;
source2.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source2.journal = 'Flora';
source2.number = 272;
source2.pages = 151702;
source2.figure = '8C';
source2.obtainingMethod = 'opticalMicroscope';
Mimosa_dryandroides_var_dryandroides.stems.trichomes.granular.addSource(source2);
