"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_glazioui = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Leaf_1 = require("../../characters/v1/Leaf");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Capitate_1 = require("../../characters/v1/Trichomes/Capitate");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Stipule_1 = require("../../characters/v1/Stipule");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Fruit_1 = require("../../characters/v1/Fruit");
var Androecium_1 = require("../../characters/v1/Androecium");
var Ginoecium_1 = require("../../characters/v1/Ginoecium");
var Seed_1 = require("../../characters/v1/Seed");
// Import annotation classes
var v1_2 = require("../../characters/v1");
// Description of Mimosa glazioui
var Mimosa_glazioui = new _1.Mimosa();
exports.Mimosa_glazioui = Mimosa_glazioui;
Mimosa_glazioui.specificEpithet = 'glazioui';
Mimosa_glazioui.stems = new v1_1.Stems();
Mimosa_glazioui.stems.trichomes = new v1_1.Trichomes();
Mimosa_glazioui.stems.trichomes.setiform = new Trichomes_1.Setiform();
Mimosa_glazioui.stems.trichomes.setiform.are = 'present';
Mimosa_glazioui.stems.trichomes.capitate = new Trichomes_1.Capitate();
Mimosa_glazioui.stems.trichomes.capitate.filiform = new Capitate_1.CapitateFiliform();
Mimosa_glazioui.stipule = new v1_1.Stipule();
Mimosa_glazioui.stipule.margin = new Stipule_1.MarginStipule();
Mimosa_glazioui.stipule.adaxial = new Stipule_1.AdaxialStipule();
Mimosa_glazioui.stipule.abaxial = new Stipule_1.AbaxialStipule();
Mimosa_glazioui.leaf = new v1_1.Leaf();
Mimosa_glazioui.leaf.petiole = new Leaf_1.Petiole();
Mimosa_glazioui.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_glazioui.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_glazioui.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_glazioui.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_glazioui.leaf.bipinnate.pinnae.setNumberOfPairsRarelyMin(1);
Mimosa_glazioui.leaf.bipinnate.pinnae.setNumberOfPairsMinMax(2, 4);
Mimosa_glazioui.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_glazioui.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_glazioui.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_glazioui.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(14, 18);
Mimosa_glazioui.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsRarelyMin(19);
Mimosa_glazioui.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_glazioui.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_glazioui.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_glazioui.inflorescence = new v1_1.Inflorescence();
Mimosa_glazioui.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_glazioui.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_glazioui.flower = new v1_1.Flower();
Mimosa_glazioui.flower.bracteole = new Flower_1.Bracteole();
Mimosa_glazioui.flower.merism = '4-merous';
Mimosa_glazioui.flower.numberWhorlsOfStamens = 'isostemonous';
Mimosa_glazioui.flower.calyx = new Flower_1.Calyx();
Mimosa_glazioui.flower.calyx.shape = 'campanulate';
Mimosa_glazioui.flower.corolla = new Flower_1.Corolla();
Mimosa_glazioui.flower.corolla.shape = 'campanulate';
Mimosa_glazioui.androecium = new v1_1.Androecium();
Mimosa_glazioui.androecium.filaments = new Androecium_1.Filaments();
Mimosa_glazioui.androecium.filaments.colour = 'whitenish';
Mimosa_glazioui.ginoecium = new v1_1.Ginoecium();
Mimosa_glazioui.ginoecium.ovary = new Ginoecium_1.Ovary();
Mimosa_glazioui.fruit = new v1_1.Fruit();
Mimosa_glazioui.fruit.stipe = new Fruit_1.Stipe();
Mimosa_glazioui.fruit.replum = new Fruit_1.Replum();
Mimosa_glazioui.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_glazioui.seed = new Seed_1.Seed();
// Description authorship
Mimosa_glazioui.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_glazioui.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source0 = new v1_2.Source();
source0.sourceType = 'article';
source0.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source0.year = 2018;
source0.title = 'Toward a Census of *Mimosa* (Leguminosae) in the Atlantic Domain, Southeastern Brazil';
source0.journal = 'Systematic Botany';
source0.volume = 43;
source0.number = 1;
source0.pages = 162 - 197;
Mimosa_glazioui.addSource(source0);
/// Trichomes
var source1 = new v1_2.Source();
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source1.year = 2020;
source1.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source1.journal = 'Flora';
source1.number = 272;
source1.pages = 151702;
source1.figure = '2E';
source1.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_glazioui.stems.trichomes.setiform.addSource(source1);
var source2 = new v1_2.Source();
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source2.year = 2020;
source2.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source2.journal = 'Flora';
source2.number = 272;
source2.pages = 151702;
source2.figure = '8E';
source2.obtainingMethod = 'opticalMicroscope';
Mimosa_glazioui.stems.trichomes.setiform.addSource(source2);
