"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_pigra_var_pigra = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Leaf_1 = require("../../characters/v1/Leaf");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Stipule_1 = require("../../characters/v1/Stipule");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Fruit_1 = require("../../characters/v1/Fruit");
var Androecium_1 = require("../../characters/v1/Androecium");
var Ginoecium_1 = require("../../characters/v1/Ginoecium");
var Seed_1 = require("../../characters/v1/Seed");
// Import annotation classes
var v1_2 = require("../../characters/v1");
var Setiform_1 = require("../../characters/v1/Trichomes/Setiform");
// Description of Mimosa pigra_var_pigra
var Mimosa_pigra_var_pigra = new _1.Mimosa();
exports.Mimosa_pigra_var_pigra = Mimosa_pigra_var_pigra;
Mimosa_pigra_var_pigra.specificEpithet = 'pigra var. pigra';
Mimosa_pigra_var_pigra.stems = new v1_1.Stems();
Mimosa_pigra_var_pigra.stems.trichomes = new v1_1.Trichomes();
Mimosa_pigra_var_pigra.stems.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_pigra_var_pigra.stems.trichomes.filiform.are = 'present';
Mimosa_pigra_var_pigra.stems.trichomes.setiform = new Trichomes_1.Setiform();
Mimosa_pigra_var_pigra.stems.trichomes.setiform.barbellate = new Setiform_1.SetiformBarbellate();
Mimosa_pigra_var_pigra.stems.trichomes.setiform.barbellate.are = 'present';
Mimosa_pigra_var_pigra.stipule = new v1_1.Stipule();
Mimosa_pigra_var_pigra.stipule.margin = new Stipule_1.MarginStipule();
Mimosa_pigra_var_pigra.stipule.adaxial = new Stipule_1.AdaxialStipule();
Mimosa_pigra_var_pigra.stipule.abaxial = new Stipule_1.AbaxialStipule();
Mimosa_pigra_var_pigra.leaf = new v1_1.Leaf();
Mimosa_pigra_var_pigra.leaf.petiole = new Leaf_1.Petiole();
Mimosa_pigra_var_pigra.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_pigra_var_pigra.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_pigra_var_pigra.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_pigra_var_pigra.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_pigra_var_pigra.leaf.bipinnate.pinnae.setNumberOfPairsMinMax(7, 18);
Mimosa_pigra_var_pigra.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_pigra_var_pigra.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_pigra_var_pigra.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_pigra_var_pigra.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(7, 18);
Mimosa_pigra_var_pigra.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_pigra_var_pigra.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_pigra_var_pigra.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_pigra_var_pigra.inflorescence = new v1_1.Inflorescence();
Mimosa_pigra_var_pigra.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_pigra_var_pigra.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_pigra_var_pigra.flower = new v1_1.Flower();
Mimosa_pigra_var_pigra.flower.bracteole = new Flower_1.Bracteole();
Mimosa_pigra_var_pigra.flower.merism = '4-merous';
Mimosa_pigra_var_pigra.flower.numberWhorlsOfStamens = 'diplostemonous';
Mimosa_pigra_var_pigra.flower.calyx = new Flower_1.Calyx();
Mimosa_pigra_var_pigra.flower.calyx.shape = 'pappiform';
Mimosa_pigra_var_pigra.flower.corolla = new Flower_1.Corolla();
Mimosa_pigra_var_pigra.flower.corolla.shape = 'campanulate';
Mimosa_pigra_var_pigra.androecium = new v1_1.Androecium();
Mimosa_pigra_var_pigra.androecium.filaments = new Androecium_1.Filaments();
Mimosa_pigra_var_pigra.androecium.filaments.colour = 'whitenish';
Mimosa_pigra_var_pigra.ginoecium = new v1_1.Ginoecium();
Mimosa_pigra_var_pigra.ginoecium.ovary = new Ginoecium_1.Ovary();
Mimosa_pigra_var_pigra.fruit = new v1_1.Fruit();
Mimosa_pigra_var_pigra.fruit.stipe = new Fruit_1.Stipe();
Mimosa_pigra_var_pigra.fruit.replum = new Fruit_1.Replum();
Mimosa_pigra_var_pigra.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_pigra_var_pigra.seed = new Seed_1.Seed();
// Description authorship
Mimosa_pigra_var_pigra.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_pigra_var_pigra.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source0 = new v1_2.Source();
source0.sourceType = 'article';
source0.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source0.year = 2018;
source0.title = 'Toward a Census of *Mimosa* (Leguminosae) in the Atlantic Domain, Southeastern Brazil';
source0.journal = 'Systematic Botany';
source0.volume = 43;
source0.number = 1;
source0.pages = '162-197';
Mimosa_pigra_var_pigra.addSource(source0);
/// Trichomes
var source1 = new v1_2.Source();
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source1.year = 2020;
source1.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source1.journal = 'Flora';
source1.number = 272;
source1.pages = '151702';
source1.figure = '3D';
source1.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_pigra_var_pigra.stems.trichomes.setiform.addSource(source1);
var source2 = new v1_2.Source();
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source2.year = 2020;
source2.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source2.journal = 'Flora';
source2.number = 272;
source2.pages = '151702';
source2.figure = '3E';
source2.obtainingMethod = 'stereoscope';
Mimosa_pigra_var_pigra.stems.trichomes.setiform.addSource(source2);
var source3 = new v1_2.Source();
source3.sourceType = 'article';
source3.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source3.year = 2020;
source3.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source3.journal = 'Flora';
source3.number = 272;
source3.pages = '151702';
source3.figure = '3F';
source3.obtainingMethod = 'opticalMicroscope';
Mimosa_pigra_var_pigra.stems.trichomes.setiform.addSource(source3);
