"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_cubatanensis = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Leaf_1 = require("../../characters/v1/Leaf");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
// Import annotation classes
var v1_2 = require("../../characters/v1");
var Fruit_1 = require("../../characters/v1/Fruit");
var Stipule_1 = require("../../characters/v1/Stipule");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Androecium_1 = require("../../characters/v1/Androecium");
var Ginoecium_1 = require("../../characters/v1/Ginoecium");
// Description of Mimosa cubatanensis
var Mimosa_cubatanensis = new _1.Mimosa();
exports.Mimosa_cubatanensis = Mimosa_cubatanensis;
Mimosa_cubatanensis.specificEpithet = 'cubatanensis';
Mimosa_cubatanensis.stems = new v1_1.Stems();
Mimosa_cubatanensis.stems.trichomes = new v1_1.Trichomes();
Mimosa_cubatanensis.stems.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_cubatanensis.stems.trichomes.filiform.are = 'present';
Mimosa_cubatanensis.stipule = new v1_1.Stipule();
Mimosa_cubatanensis.stipule.margin = new Stipule_1.MarginStipule();
Mimosa_cubatanensis.stipule.adaxial = new Stipule_1.AdaxialStipule();
Mimosa_cubatanensis.stipule.abaxial = new Stipule_1.AbaxialStipule();
Mimosa_cubatanensis.leaf = new v1_1.Leaf();
Mimosa_cubatanensis.leaf.petiole = new Leaf_1.Petiole();
Mimosa_cubatanensis.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_cubatanensis.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_cubatanensis.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_cubatanensis.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_cubatanensis.leaf.bipinnate.pinnae.setNumberOfPairsMinMax(3, 5);
Mimosa_cubatanensis.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_cubatanensis.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_cubatanensis.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_cubatanensis.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(8, 14);
Mimosa_cubatanensis.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_cubatanensis.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_cubatanensis.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes = new v1_1.Trichomes();
Mimosa_cubatanensis.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_cubatanensis.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.filiform.are = 'present';
Mimosa_cubatanensis.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.filiform.orientation = 'antrorse-appressed';
Mimosa_cubatanensis.inflorescence = new v1_1.Inflorescence();
Mimosa_cubatanensis.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_cubatanensis.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_cubatanensis.flower = new v1_1.Flower();
Mimosa_cubatanensis.flower.bracteole = new Flower_1.Bracteole();
Mimosa_cubatanensis.flower.merism = '4-merous';
Mimosa_cubatanensis.flower.numberWhorlsOfStamens = 'diplostemonous';
Mimosa_cubatanensis.flower.calyx = new Flower_1.Calyx();
Mimosa_cubatanensis.flower.calyx.shape = 'campanulate';
Mimosa_cubatanensis.flower.corolla = new Flower_1.Corolla();
Mimosa_cubatanensis.flower.corolla.shape = 'campanulate';
Mimosa_cubatanensis.androecium = new v1_1.Androecium();
Mimosa_cubatanensis.androecium.filaments = new Androecium_1.Filaments();
Mimosa_cubatanensis.androecium.filaments.colour = 'whitenish';
Mimosa_cubatanensis.ginoecium = new v1_1.Ginoecium();
Mimosa_cubatanensis.ginoecium.ovary = new Ginoecium_1.Ovary();
Mimosa_cubatanensis.fruit = new Fruit_1.Fruit();
Mimosa_cubatanensis.fruit.stipe = new Fruit_1.Stipe();
Mimosa_cubatanensis.fruit.replum = new Fruit_1.Replum();
Mimosa_cubatanensis.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_cubatanensis.seed = new v1_1.Seed();
// Description authorship
Mimosa_cubatanensis.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_cubatanensis.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source0 = new v1_2.Source();
source0.sourceType = 'article';
source0.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source0.year = 2018;
source0.title = 'Toward a Census of *Mimosa* (Leguminosae) in the Atlantic Domain, Southeastern Brazil';
source0.journal = 'Systematic Botany';
source0.volume = 43;
source0.number = 1;
source0.pages = 162 - 197;
Mimosa_cubatanensis.addSource(source0);
/// Trichomes
var source1 = new v1_2.Source();
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source1.year = 2020;
source1.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source1.journal = 'Flora';
source1.number = 272;
source1.pages = 151702;
source1.figure = '1B';
source1.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_cubatanensis.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.filiform.addSource(source1);
var source2 = new v1_2.Source();
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source2.year = 2020;
source2.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source2.journal = 'Flora';
source2.number = 272;
source2.pages = 151702;
source2.figure = '1H';
source2.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_cubatanensis.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.filiform.addSource(source2);
var source3 = new v1_2.Source();
source3.sourceType = 'article';
source3.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source3.year = 2020;
source3.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source3.journal = 'Flora';
source3.number = 272;
source3.pages = 151702;
source3.figure = '9P';
source3.obtainingMethod = 'stereoscope';
Mimosa_cubatanensis.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.filiform.addSource(source3);
