"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_osmarii = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Leaf_1 = require("../../characters/v1/Leaf");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Stipule_1 = require("../../characters/v1/Stipule");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Corolla_1 = require("../../characters/v1/Flower/Corolla");
var Fruit_1 = require("../../characters/v1/Fruit");
var Androecium_1 = require("../../characters/v1/Androecium");
var Filaments_1 = require("../../characters/v1/Androecium/Filaments");
var baseFilaments_1 = require("../../characters/v1/Androecium/Filaments/baseFilaments");
var Ginoecium_1 = require("../../characters/v1/Ginoecium");
// Import annotation classes
var v1_2 = require("../../characters/v1");
var Paraphillidia_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Paraphillidia");
// Description of Mimosa osmarii
var Mimosa_osmarii = new _1.Mimosa();
exports.Mimosa_osmarii = Mimosa_osmarii;
Mimosa_osmarii.specificEpithet = 'osmarii';
Mimosa_osmarii.habit = 'herb';
Mimosa_osmarii.lightStrategy = ['sciophilous', 'semisciophilous'];
Mimosa_osmarii.stems = new v1_1.Stems();
Mimosa_osmarii.stems.orientation = 'scandent';
Mimosa_osmarii.stems.trichomes = new v1_1.Trichomes;
Mimosa_osmarii.stems.trichomes.granular = new Trichomes_1.Granular();
Mimosa_osmarii.stems.trichomes.granular.are = 'present';
Mimosa_osmarii.stems.prickles = new v1_1.Prickles();
Mimosa_osmarii.stems.prickles.orientation = 'decurved';
Mimosa_osmarii.stems.prickles.setLength(2);
Mimosa_osmarii.stipule = new v1_1.Stipule();
Mimosa_osmarii.stipule.setLengthMinMax(0.8, 2);
Mimosa_osmarii.stipule.shape = 'lanceolate';
Mimosa_osmarii.stipule.nervation = '1-nerved';
Mimosa_osmarii.stipule.persistance = 'persistent';
Mimosa_osmarii.stipule.margin = new Stipule_1.MarginStipule();
Mimosa_osmarii.stipule.margin.trichomes = new v1_1.Trichomes();
Mimosa_osmarii.stipule.margin.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_osmarii.stipule.margin.trichomes.filiform.are = 'present or absent';
Mimosa_osmarii.stipule.abaxial = new Stipule_1.AbaxialStipule();
Mimosa_osmarii.stipule.abaxial.trichomes = new v1_1.Trichomes();
Mimosa_osmarii.stipule.abaxial.trichomes.granular = new Trichomes_1.Granular();
Mimosa_osmarii.stipule.abaxial.trichomes.granular.are = 'present or absent';
Mimosa_osmarii.leaf = new v1_1.Leaf();
Mimosa_osmarii.leaf.petiole = new Leaf_1.Petiole();
Mimosa_osmarii.leaf.petiole.setLengthMinMax(13, 35);
Mimosa_osmarii.leaf.petiole.transversalShape = '4-ribbed';
Mimosa_osmarii.leaf.petiole.prickles = new v1_1.Prickles();
Mimosa_osmarii.leaf.petiole.prickles.orientation = 'decurved';
Mimosa_osmarii.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_osmarii.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_osmarii.leaf.bipinnate.rachis.setLengthMinMax(5, 35);
Mimosa_osmarii.leaf.bipinnate.rachis.prickles = new v1_1.Prickles();
Mimosa_osmarii.leaf.bipinnate.rachis.prickles.are = 'present';
Mimosa_osmarii.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_osmarii.leaf.bipinnate.rachis.spicule.is = 'present or absent';
Mimosa_osmarii.leaf.bipinnate.rachis.spicule.setLengthMinMax(1, 1.5);
Mimosa_osmarii.leaf.bipinnate.rachis.spicule.shape = 'deltate';
Mimosa_osmarii.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_osmarii.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_osmarii.leaf.bipinnate.pinnae.paraphillidia.are = 'present';
Mimosa_osmarii.leaf.bipinnate.pinnae.paraphillidia.setLengthMinMax(0.2, 3);
Mimosa_osmarii.leaf.bipinnate.pinnae.paraphillidia.pairLength = 'equal';
Mimosa_osmarii.leaf.bipinnate.pinnae.paraphillidia.shape = ['lanceolate', 'linear'];
Mimosa_osmarii.leaf.bipinnate.pinnae.paraphillidia.position = [
    'closer to the first pair of leaflets',
    'on the middle of the axis, between the pulvinus and the first pair of leaflets'
];
Mimosa_osmarii.leaf.bipinnate.pinnae.paraphillidia.distanceFromPinnaPulvinus = new Paraphillidia_1.DistanceFromPinnaPulvinus();
Mimosa_osmarii.leaf.bipinnate.pinnae.paraphillidia.distanceFromPinnaPulvinus.setLengthMinMax(1, 5.5);
Mimosa_osmarii.leaf.bipinnate.pinnae.paraphillidia.distanceFromFirstPairOfLeaflets = new Paraphillidia_1.DistanceFromFirstPairOfLeaflets();
Mimosa_osmarii.leaf.bipinnate.pinnae.paraphillidia.distanceFromFirstPairOfLeaflets.setLengthMinMax(1.1, 3);
Mimosa_osmarii.leaf.bipinnate.pinnae.setNumberOfPairsRarelyMin(1);
Mimosa_osmarii.leaf.bipinnate.pinnae.setNumberOfPairsMinMax(2, 4);
Mimosa_osmarii.leaf.bipinnate.pinnae.prickles = new v1_1.Prickles();
Mimosa_osmarii.leaf.bipinnate.pinnae.prickles.orientation = 'decurved';
Mimosa_osmarii.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_osmarii.leaf.bipinnate.pinnae.rachilla.prickles = new v1_1.Prickles();
Mimosa_osmarii.leaf.bipinnate.pinnae.rachilla.prickles.are = 'present';
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(2, 3);
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.innermostOfProximalPairReduced = 'yes';
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.setHeightMinMax(2, 7.5);
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.setWidthMinMax(1.3, 4.1);
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.shape = 'obovate';
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.base = ['oblique-acute', 'oblique-rounded', 'oblique-subcordate'];
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.apex = ['obtuse-mucronulate', 'rounded-mucronulate'];
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.margin.trichomes = new v1_1.Trichomes();
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.margin.trichomes.are = 'absent';
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.adaxial.trichomes = new v1_1.Trichomes();
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.adaxial.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.adaxial.trichomes.filiform.are = 'present';
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.adaxial.trichomes.granular = new Trichomes_1.Granular();
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.adaxial.trichomes.granular.are = 'present or absent';
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes = new v1_1.Trichomes();
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.granular = new Trichomes_1.Granular();
Mimosa_osmarii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.granular.are = 'present or absent';
Mimosa_osmarii.inflorescence = new v1_1.Inflorescence();
Mimosa_osmarii.inflorescence.shape = 'moriform';
Mimosa_osmarii.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_osmarii.inflorescence.capitate.shape = 'globose';
Mimosa_osmarii.inflorescence.capitate.setLengthMinMax(2.5, 6);
Mimosa_osmarii.inflorescence.capitate.numberPerNode = [1, 2, 3];
Mimosa_osmarii.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_osmarii.inflorescence.peduncle.setLengthMinMax(18, 40);
Mimosa_osmarii.flower = new v1_1.Flower();
Mimosa_osmarii.flower.bracteole = new Flower_1.Bracteole();
Mimosa_osmarii.flower.bracteole.setLengthMinMax(0.4, 0.9);
Mimosa_osmarii.flower.bracteole.shape = 'lanceolate';
Mimosa_osmarii.flower.bracteole.trichomes = new v1_1.Trichomes();
Mimosa_osmarii.flower.bracteole.trichomes.granular = new Trichomes_1.Granular();
Mimosa_osmarii.flower.bracteole.trichomes.granular.are = 'present or absent';
Mimosa_osmarii.flower.merism = '4-merous';
Mimosa_osmarii.flower.merismRarely = '5-merous';
Mimosa_osmarii.flower.calyx = new Flower_1.Calyx();
Mimosa_osmarii.flower.calyx.setLengthMinMax(0.4, 0.6);
Mimosa_osmarii.flower.calyx.shape = 'campanulate';
Mimosa_osmarii.flower.calyx.apex = 'shortly denticulate';
Mimosa_osmarii.flower.corolla = new Flower_1.Corolla();
Mimosa_osmarii.flower.corolla.setLengthMinMax(2, 2.5);
Mimosa_osmarii.flower.corolla.shape = ['campanulate', 'turbinate'];
Mimosa_osmarii.flower.corolla.lobes = new Corolla_1.Lobes();
Mimosa_osmarii.flower.corolla.lobes.nervation = '1-nerved';
Mimosa_osmarii.androecium = new v1_1.Androecium();
Mimosa_osmarii.androecium.filaments = new Androecium_1.Filaments();
Mimosa_osmarii.androecium.filaments.setLengthMinMax(6, 6.5);
Mimosa_osmarii.androecium.filaments.base = new Filaments_1.baseFilaments();
Mimosa_osmarii.androecium.filaments.base.connation = new baseFilaments_1.ConnationOfFilamentsAtBase();
Mimosa_osmarii.androecium.filaments.base.connation.setLengthMinMax(0.2, 0.5);
Mimosa_osmarii.androecium.filaments.colour = 'pinkish';
Mimosa_osmarii.ginoecium = new v1_1.Ginoecium();
Mimosa_osmarii.ginoecium.ovary = new Ginoecium_1.Ovary();
Mimosa_osmarii.ginoecium.ovary.trichomes = new v1_1.Trichomes();
Mimosa_osmarii.ginoecium.ovary.trichomes.are = 'absent';
Mimosa_osmarii.fruit = new v1_1.Fruit();
Mimosa_osmarii.fruit.type = 'craspedium';
Mimosa_osmarii.fruit.setHeightMinMax(34, 38);
Mimosa_osmarii.fruit.setWidthMinMax(3.3, 3.5);
Mimosa_osmarii.fruit.shape = 'oblong';
Mimosa_osmarii.fruit.curvature = 'slightly curved';
Mimosa_osmarii.fruit.stipe = new Fruit_1.Stipe();
Mimosa_osmarii.fruit.stipe.is = 'present';
Mimosa_osmarii.fruit.stipe.setLengthMinMax(3, 5);
Mimosa_osmarii.fruit.replum = new Fruit_1.Replum();
Mimosa_osmarii.fruit.replum.shape = 'undulate';
Mimosa_osmarii.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_osmarii.fruit.epicarp.type = 'monospermic';
Mimosa_osmarii.fruit.epicarp.trichomes = new v1_1.Trichomes();
Mimosa_osmarii.fruit.epicarp.trichomes.granular = new Trichomes_1.Granular();
Mimosa_osmarii.fruit.epicarp.trichomes.granular.are = 'present';
Mimosa_osmarii.fruit.setNumberOfSeedsMinMax(6, 9);
// Description authorship
Mimosa_osmarii.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_osmarii.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source1 = new v1_2.Source();
source1.obraPrinceps = 'yes';
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A. & Simon, M.F.';
source1.year = 2017;
source1.title = 'A new species of *Mimosa* (Leguminosae) endemic to the Brazilian Cerrado';
source1.journal = 'Phytotaxa';
source1.volume = 312;
source1.number = 2;
source1.pages = 237 - 246;
Mimosa_osmarii.addSource(source1);
var source2 = new v1_2.Source();
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A. & Simon, M.F.';
source2.year = 2017;
source2.title = 'A new species of *Mimosa* (Leguminosae) endemic to the Brazilian Cerrado';
source2.journal = 'Phytotaxa';
source2.volume = 312;
source2.number = 2;
source2.pages = 237 - 246;
source2.figure = '3A,B,C,D';
source2.obtainingMethod = 'photo';
Mimosa_osmarii.addSource(source2);
var source3 = new v1_2.Source();
source3.sourceType = 'article';
source3.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A. & Simon, M.F.';
source3.year = 2017;
source3.title = 'A new species of *Mimosa* (Leguminosae) endemic to the Brazilian Cerrado';
source3.journal = 'Phytotaxa';
source3.volume = 312;
source3.number = 2;
source3.pages = 237 - 246;
source3.figure = '4';
source3.obtainingMethod = 'drawing';
Mimosa_osmarii.addSource(source3);
