"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_emaensis = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Leaf_1 = require("../../characters/v1/Leaf");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Androecium_1 = require("../../characters/v1/Androecium");
var Filaments_1 = require("../../characters/v1/Androecium/Filaments");
var baseFilaments_1 = require("../../characters/v1/Androecium/Filaments/baseFilaments");
var Fruit_1 = require("../../characters/v1/Fruit");
// Import anotations classes
var v1_2 = require("../../characters/v1");
var Paraphillidia_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Paraphillidia");
// Description of Mimosa emaensis
var Mimosa_emaensis = new _1.Mimosa();
exports.Mimosa_emaensis = Mimosa_emaensis;
Mimosa_emaensis.specificEpithet = 'emaensis';
Mimosa_emaensis.habit = ['herb', 'subshrub'];
Mimosa_emaensis.height = 0.5;
Mimosa_emaensis.prickles = new v1_1.Prickles();
Mimosa_emaensis.prickles.are = 'absent';
Mimosa_emaensis.trichomes = new v1_1.Trichomes();
Mimosa_emaensis.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_emaensis.trichomes.filiform.are = 'absent';
Mimosa_emaensis.trichomes.setiform = new Trichomes_1.Setiform();
Mimosa_emaensis.trichomes.setiform.are = 'absent';
Mimosa_emaensis.stems = new v1_1.Stems();
Mimosa_emaensis.stems.shape = 'cylindric';
Mimosa_emaensis.stipule = new v1_1.Stipule();
Mimosa_emaensis.stipule.setLengthRarelyMin(1.5);
Mimosa_emaensis.stipule.setLengthMinMax(3.5, 9);
Mimosa_emaensis.stipule.shape = ['linear-subulate', 'lanceolate'];
Mimosa_emaensis.stipule.nervation = '1-nerved';
Mimosa_emaensis.stipule.persistance = 'persistent';
Mimosa_emaensis.leaf = new v1_1.Leaf();
Mimosa_emaensis.leaf.petiole = new Leaf_1.Petiole();
Mimosa_emaensis.leaf.petiole.setLengthMinMax(14, 35);
Mimosa_emaensis.leaf.petiole.transversalShape = '5-ribbed';
Mimosa_emaensis.leaf.petiole.flattening = 'slightly dorsiventrally flattened';
Mimosa_emaensis.leaf.petiole.persistance = 'persistent';
Mimosa_emaensis.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_emaensis.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_emaensis.leaf.bipinnate.rachis.setLengthMinMax(22, 40);
Mimosa_emaensis.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_emaensis.leaf.bipinnate.pinnae.setNumberOfPairsRarelyMin(5);
Mimosa_emaensis.leaf.bipinnate.pinnae.setNumberOfPairsMinMax(6, 8);
Mimosa_emaensis.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_emaensis.leaf.bipinnate.pinnae.rachilla.setLengthMinMax(0.2, 0.3);
Mimosa_emaensis.leaf.bipinnate.pinnae.rachilla.setLengthRarelyMax(0.5);
Mimosa_emaensis.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_emaensis.leaf.bipinnate.pinnae.paraphillidia.setLengthMinMax(0.3, 0.6);
Mimosa_emaensis.leaf.bipinnate.pinnae.paraphillidia.shape = ['lanceolate', 'linear-subulate'];
Mimosa_emaensis.leaf.bipinnate.pinnae.paraphillidia.distanceFromFirstPairOfLeaflets = new Paraphillidia_1.DistanceFromFirstPairOfLeaflets();
Mimosa_emaensis.leaf.bipinnate.pinnae.paraphillidia.distanceFromFirstPairOfLeaflets.setLengthMinMax(0.5, 1.8);
Mimosa_emaensis.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_emaensis.leaf.bipinnate.pinnae.leaflet.setNumberOfPairs(2);
Mimosa_emaensis.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsRarelyMax(3);
Mimosa_emaensis.leaf.bipinnate.pinnae.leaflet.setHeightMinMax(0.9, 1.8);
Mimosa_emaensis.leaf.bipinnate.pinnae.leaflet.setWidthMinMax(0.3, 1);
Mimosa_emaensis.leaf.bipinnate.pinnae.leaflet.shape = 'obovate';
Mimosa_emaensis.leaf.bipinnate.pinnae.leaflet.base = ['oblique-acute', 'oblique-subcordate'];
Mimosa_emaensis.leaf.bipinnate.pinnae.leaflet.apex = ['obtuse', 'obtuse-mucronulate', 'rounded', 'rounded-mucronulate'];
Mimosa_emaensis.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_emaensis.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_emaensis.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_emaensis.inflorescence = new v1_1.Inflorescence();
Mimosa_emaensis.inflorescence.shape = 'moriform';
Mimosa_emaensis.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_emaensis.inflorescence.peduncle.setLengthMinMax(47, 65);
Mimosa_emaensis.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_emaensis.inflorescence.capitate.setLengthMinMax(3.5, 5);
Mimosa_emaensis.inflorescence.capitate.shape = 'globose';
Mimosa_emaensis.flower = new v1_1.Flower();
Mimosa_emaensis.flower.bracteole = new Flower_1.Bracteole();
Mimosa_emaensis.flower.bracteole.setLengthMinMax(0.9, 1.1);
Mimosa_emaensis.flower.bracteole.shape = ['linear', 'lanceolate', 'spatulate'];
Mimosa_emaensis.flower.bracteole.trichomes = new v1_1.Trichomes();
Mimosa_emaensis.flower.bracteole.trichomes.granular = new Trichomes_1.Granular();
Mimosa_emaensis.flower.bracteole.trichomes.granular.are = 'present or absent';
Mimosa_emaensis.flower.merism = '4-merous';
Mimosa_emaensis.flower.calyx = new Flower_1.Calyx();
Mimosa_emaensis.flower.calyx.setLengthMinMax(0.4, 0.5);
Mimosa_emaensis.flower.calyx.shape = 'campanulate';
Mimosa_emaensis.flower.calyx.apex = 'denticulate';
Mimosa_emaensis.flower.calyx.trichomes = new v1_1.Trichomes();
Mimosa_emaensis.flower.calyx.trichomes.granular = new Trichomes_1.Granular();
Mimosa_emaensis.flower.calyx.trichomes.granular.are = 'present or absent';
Mimosa_emaensis.flower.corolla = new Flower_1.Corolla();
Mimosa_emaensis.flower.corolla.setLengthMinMax(2, 2.5);
Mimosa_emaensis.flower.corolla.shape = 'turbinate';
Mimosa_emaensis.flower.corolla.trichomes = new v1_1.Trichomes();
Mimosa_emaensis.flower.corolla.trichomes.granular = new Trichomes_1.Granular();
Mimosa_emaensis.flower.corolla.trichomes.granular.are = 'present or absent';
Mimosa_emaensis.androecium = new v1_1.Androecium();
Mimosa_emaensis.androecium.filaments = new Androecium_1.Filaments();
Mimosa_emaensis.androecium.filaments.setLengthMinMax(4, 5);
Mimosa_emaensis.androecium.filaments.colour = 'pinkish';
Mimosa_emaensis.androecium.filaments.base = new Filaments_1.baseFilaments();
Mimosa_emaensis.androecium.filaments.base.connation = new baseFilaments_1.ConnationOfFilamentsAtBase();
Mimosa_emaensis.androecium.filaments.base.connation.setLength(0.2);
Mimosa_emaensis.fruit = new v1_1.Fruit();
Mimosa_emaensis.fruit.setHeightMinMax(21, 65);
Mimosa_emaensis.fruit.setWidthMinMax(6.5, 7.5);
Mimosa_emaensis.fruit.stipe = new Fruit_1.Stipe();
Mimosa_emaensis.fruit.stipe.is = 'present or absent';
Mimosa_emaensis.fruit.stipe.setLength(2);
Mimosa_emaensis.fruit.shape = 'oblong';
Mimosa_emaensis.fruit.curvature = 'straight';
Mimosa_emaensis.fruit.replum = new Fruit_1.Replum();
Mimosa_emaensis.fruit.replum.shape = 'undulate';
Mimosa_emaensis.fruit.replum.trichomes = new v1_1.Trichomes();
Mimosa_emaensis.fruit.replum.trichomes.granular = new Trichomes_1.Granular();
Mimosa_emaensis.fruit.replum.trichomes.granular.are = 'present';
Mimosa_emaensis.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_emaensis.fruit.epicarp.trichomes = new v1_1.Trichomes();
Mimosa_emaensis.fruit.epicarp.trichomes.granular = new Trichomes_1.Granular();
Mimosa_emaensis.fruit.epicarp.trichomes.granular.are = 'present';
Mimosa_emaensis.fruit.setNumberOfSeedsRarelyMin(2);
Mimosa_emaensis.fruit.setNumberOfSeedsMinMax(3, 8);
Mimosa_emaensis.seed = new v1_1.Seed();
Mimosa_emaensis.seed.setHeightMinMax(4, 4.5);
Mimosa_emaensis.seed.setWidthMinMax(3.2, 3.3);
Mimosa_emaensis.seed.shape = 'obovate';
Mimosa_emaensis.seed.pleurogram = 'apical-basal';
// Description authorship
Mimosa_emaensis.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_emaensis.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source1 = new v1_2.Source();
source1.obraPrinceps = 'yes';
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. and Morim, M.P. and Simon, M.F., Dutra, V.F. and Baumgratz, J.F.A.';
source1.year = 2021;
source1.title = 'New Species of *Mimosa* (Leguminosae) from Brazil';
source1.journal = 'Systematic Botany';
source1.volume = 46;
source1.number = 2;
source1.pages = 339 - 351;
Mimosa_emaensis.addSource(source1);
var source2 = new v1_2.Source();
source2.obraPrinceps = 'yes';
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. and Morim, M.P. and Simon, M.F., Dutra, V.F. and Baumgratz, J.F.A.';
source2.year = 2021;
source2.title = 'New Species of *Mimosa* (Leguminosae) from Brazil';
source2.journal = 'Systematic Botany';
source2.volume = 46;
source2.number = 2;
source2.pages = 339 - 351;
source2.figure = '4';
source2.obtainingMethod = 'drawing';
Mimosa_emaensis.addSource(source2);
var source3 = new v1_2.Source();
source3.obraPrinceps = 'yes';
source3.sourceType = 'article';
source3.authorship = 'Jordão, L.S.B. and Morim, M.P. and Simon, M.F., Dutra, V.F. and Baumgratz, J.F.A.';
source3.year = 2021;
source3.title = 'New Species of *Mimosa* (Leguminosae) from Brazil';
source3.journal = 'Systematic Botany';
source3.volume = 46;
source3.number = 2;
source3.pages = 339 - 351;
source3.figure = '5';
source3.obtainingMethod = 'photo';
Mimosa_emaensis.addSource(source3);
