"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_robsonii = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Leaf_1 = require("../../characters/v1/Leaf");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Fruit_1 = require("../../characters/v1/Fruit");
var Androecium_1 = require("../../characters/v1/Androecium");
// Import annotation classes
var v1_2 = require("../../characters/v1");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Paraphillidia_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Paraphillidia");
var Filaments_1 = require("../../characters/v1/Androecium/Filaments");
var baseFilaments_1 = require("../../characters/v1/Androecium/Filaments/baseFilaments");
// Description of Mimosa robsonii
var Mimosa_robsonii = new _1.Mimosa();
exports.Mimosa_robsonii = Mimosa_robsonii;
Mimosa_robsonii.specificEpithet = 'robsonii';
Mimosa_robsonii.habit = 'subshrub';
Mimosa_robsonii.stems = new v1_1.Stems();
Mimosa_robsonii.stems.orientation = 'scandent';
Mimosa_robsonii.stems.length = 3;
Mimosa_robsonii.stems.shape = 'cylindric';
Mimosa_robsonii.stems.prickles = new v1_1.Prickles();
Mimosa_robsonii.stems.prickles.are = 'present';
Mimosa_robsonii.stems.prickles.frequency = 'serially armed';
Mimosa_robsonii.stems.prickles.setLength(2);
Mimosa_robsonii.stems.prickles.orientation = 'decurved';
Mimosa_robsonii.stems.trichomes = new v1_1.Trichomes();
Mimosa_robsonii.stems.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_robsonii.stems.trichomes.filiform.are = 'present';
Mimosa_robsonii.stipule = new v1_1.Stipule();
Mimosa_robsonii.stipule.setLengthMinMax(2.5, 9);
Mimosa_robsonii.stipule.shape = 'lanceolate';
Mimosa_robsonii.stipule.nervation = '1-nerved';
Mimosa_robsonii.stipule.persistance = 'persistent';
Mimosa_robsonii.stipule.trichomes = new v1_1.Trichomes();
Mimosa_robsonii.stipule.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_robsonii.stipule.trichomes.filiform.are = 'present or absent';
Mimosa_robsonii.leaf = new v1_1.Leaf();
Mimosa_robsonii.leaf.petiole = new Leaf_1.Petiole();
Mimosa_robsonii.leaf.petiole.transversalShape = '5-ribbed';
Mimosa_robsonii.leaf.petiole.persistance = 'caducous';
Mimosa_robsonii.leaf.petiole.prickles = new v1_1.Prickles();
Mimosa_robsonii.leaf.petiole.prickles.are = 'present';
Mimosa_robsonii.leaf.petiole.trichomes = new v1_1.Trichomes();
Mimosa_robsonii.leaf.petiole.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_robsonii.leaf.petiole.trichomes.filiform.are = 'present';
Mimosa_robsonii.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_robsonii.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_robsonii.leaf.bipinnate.rachis.setLengthMinMax(25, 78);
Mimosa_robsonii.leaf.bipinnate.rachis.prickles = new v1_1.Prickles();
Mimosa_robsonii.leaf.bipinnate.rachis.prickles.are = 'present';
Mimosa_robsonii.leaf.bipinnate.rachis.trichomes = new v1_1.Trichomes();
Mimosa_robsonii.leaf.bipinnate.rachis.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_robsonii.leaf.bipinnate.rachis.trichomes.filiform.are = 'present';
Mimosa_robsonii.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_robsonii.leaf.bipinnate.rachis.spicule.is = 'present or absent';
Mimosa_robsonii.leaf.bipinnate.rachis.spicule.setLengthMinMax(0.8, 1);
Mimosa_robsonii.leaf.bipinnate.rachis.spicule.shape = 'linear-subulate';
Mimosa_robsonii.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_robsonii.leaf.bipinnate.pinnae.setNumberOfPairsMinMax(4, 7);
Mimosa_robsonii.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_robsonii.leaf.bipinnate.pinnae.rachilla.setLengthMinMax(7, 48);
Mimosa_robsonii.leaf.bipinnate.pinnae.rachilla.trichomes = new v1_1.Trichomes();
Mimosa_robsonii.leaf.bipinnate.pinnae.rachilla.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_robsonii.leaf.bipinnate.pinnae.rachilla.trichomes.filiform.are = 'present';
Mimosa_robsonii.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_robsonii.leaf.bipinnate.pinnae.paraphillidia.setLengthMinMax(0.4, 1);
Mimosa_robsonii.leaf.bipinnate.pinnae.paraphillidia.shape = ['linear', 'lanceolate'];
Mimosa_robsonii.leaf.bipinnate.pinnae.paraphillidia.pairLength = 'equal';
Mimosa_robsonii.leaf.bipinnate.pinnae.paraphillidia.distanceFromFirstPairOfLeaflets = new Paraphillidia_1.DistanceFromFirstPairOfLeaflets();
Mimosa_robsonii.leaf.bipinnate.pinnae.paraphillidia.distanceFromFirstPairOfLeaflets.setLengthMinMax(0.2, 2.5);
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(6, 11);
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.setHeightMinMax(3.4, 7.5);
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.setWidthMinMax(1.6, 3);
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.shape = 'oblong';
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.base = ['oblique-rounded', 'oblique-subcordate', 'oblique-cordate'];
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.apex = ['rounded', 'obtuse'];
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.margin.trichomes = new v1_1.Trichomes();
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.margin.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.margin.trichomes.filiform.are = 'present';
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_robsonii.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_robsonii.inflorescence = new v1_1.Inflorescence();
Mimosa_robsonii.inflorescence.type = 'paniculate';
Mimosa_robsonii.inflorescence.shape = 'moriform';
Mimosa_robsonii.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_robsonii.inflorescence.capitate.setLengthMinMax(4.2, 6);
Mimosa_robsonii.inflorescence.capitate.shape = 'globose';
Mimosa_robsonii.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_robsonii.inflorescence.peduncle.setLengthMinMax(9, 17);
Mimosa_robsonii.inflorescence.peduncle.prickles = new v1_1.Prickles();
Mimosa_robsonii.inflorescence.peduncle.prickles.are = 'present';
Mimosa_robsonii.inflorescence.peduncle.trichomes = new v1_1.Trichomes();
Mimosa_robsonii.inflorescence.peduncle.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_robsonii.inflorescence.peduncle.trichomes.filiform.are = 'present';
Mimosa_robsonii.flower = new v1_1.Flower();
Mimosa_robsonii.flower.bracteole = new Flower_1.Bracteole();
Mimosa_robsonii.flower.bracteole.setLengthMinMax(1.2, 1.5);
Mimosa_robsonii.flower.bracteole.shape = 'lanceolate';
Mimosa_robsonii.flower.bracteole.trichomes = new v1_1.Trichomes();
Mimosa_robsonii.flower.bracteole.trichomes.granular = new Trichomes_1.Granular();
Mimosa_robsonii.flower.bracteole.trichomes.granular.are = 'present or absent';
Mimosa_robsonii.flower.merism = '3-merous';
Mimosa_robsonii.flower.calyx = new Flower_1.Calyx();
Mimosa_robsonii.flower.calyx.setLengthMinMax(0.4, 0.7);
Mimosa_robsonii.flower.calyx.shape = 'campanulate';
Mimosa_robsonii.flower.calyx.apex = ['shortly denticulate', 'truncate'];
Mimosa_robsonii.flower.corolla = new Flower_1.Corolla();
Mimosa_robsonii.flower.corolla.setLengthMinMax(2, 2.3);
Mimosa_robsonii.flower.corolla.shape = ['campanulate', 'turbinate'];
Mimosa_robsonii.androecium = new v1_1.Androecium();
Mimosa_robsonii.androecium.filaments = new Androecium_1.Filaments();
Mimosa_robsonii.androecium.filaments.setLengthMinMax(8, 10);
Mimosa_robsonii.androecium.filaments.colour = ['pinkish', 'whitenish'];
Mimosa_robsonii.androecium.filaments.base = new Filaments_1.baseFilaments();
Mimosa_robsonii.androecium.filaments.base.connation = new baseFilaments_1.ConnationOfFilamentsAtBase();
Mimosa_robsonii.androecium.filaments.base.connation.setLength(0.2);
Mimosa_robsonii.fruit = new v1_1.Fruit();
Mimosa_robsonii.fruit.setHeightMinMax(40, 53);
Mimosa_robsonii.fruit.setWidthMinMax(10, 12.5);
Mimosa_robsonii.fruit.stipe = new Fruit_1.Stipe();
Mimosa_robsonii.fruit.stipe.is = 'absent';
Mimosa_robsonii.fruit.shape = 'oblong';
Mimosa_robsonii.fruit.curvature = 'straight';
Mimosa_robsonii.fruit.replum = new Fruit_1.Replum();
Mimosa_robsonii.fruit.replum.shape = 'straight';
Mimosa_robsonii.fruit.replum.prickles = new v1_1.Prickles();
Mimosa_robsonii.fruit.replum.prickles.frequency = 'densely armed';
Mimosa_robsonii.fruit.replum.prickles.orientation = 'decurved';
Mimosa_robsonii.fruit.replum.prickles.setLengthMinMax(2, 4);
Mimosa_robsonii.fruit.replum.trichomes = new v1_1.Trichomes();
Mimosa_robsonii.fruit.replum.trichomes.granular = new Trichomes_1.Granular();
Mimosa_robsonii.fruit.replum.trichomes.granular.are = 'present';
Mimosa_robsonii.fruit.replum.trichomes.granular.density = 'sparsely';
Mimosa_robsonii.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_robsonii.fruit.epicarp.prickles = new v1_1.Prickles();
Mimosa_robsonii.fruit.epicarp.prickles.are = 'present';
Mimosa_robsonii.fruit.epicarp.prickles.frequency = 'sparsely armed';
Mimosa_robsonii.fruit.epicarp.prickles.orientation = 'decurved';
Mimosa_robsonii.fruit.epicarp.trichomes = new v1_1.Trichomes();
Mimosa_robsonii.fruit.epicarp.trichomes.granular = new Trichomes_1.Granular();
Mimosa_robsonii.fruit.epicarp.trichomes.granular.are = 'present';
Mimosa_robsonii.fruit.setNumberOfSeedsMinMax(8, 11);
// Description authorship
Mimosa_robsonii.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_robsonii.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source1 = new v1_2.Source();
source1.obraPrinceps = 'yes';
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. and Morim, M.P. and Simon, M.F., Dutra, V.F. and Baumgratz, J.F.A.';
source1.year = 2021;
source1.title = 'New Species of *Mimosa* (Leguminosae) from Brazil';
source1.journal = 'Systematic Botany';
source1.volume = 46;
source1.number = 2;
source1.pages = 339 - 351;
Mimosa_robsonii.addSource(source1);
var source2 = new v1_2.Source();
source2.obraPrinceps = 'yes';
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. and Morim, M.P. and Simon, M.F., Dutra, V.F. and Baumgratz, J.F.A.';
source2.year = 2021;
source2.title = 'New Species of *Mimosa* (Leguminosae) from Brazil';
source2.journal = 'Systematic Botany';
source2.volume = 46;
source2.number = 2;
source2.pages = 339 - 351;
source2.figure = '6';
source2.obtainingMethod = 'drawing';
Mimosa_robsonii.addSource(source2);
