"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_myuros = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Stellate_1 = require("../../characters/v1/Trichomes/Stellate");
var Leaf_1 = require("../../characters/v1/Leaf");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Stipule_1 = require("../../characters/v1/Stipule");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Fruit_1 = require("../../characters/v1/Fruit");
var Androecium_1 = require("../../characters/v1/Androecium");
var Ginoecium_1 = require("../../characters/v1/Ginoecium");
var Seed_1 = require("../../characters/v1/Seed");
// Import annotation classes
var v1_2 = require("../../characters/v1");
// Description of Mimosa myuros
var Mimosa_myuros = new _1.Mimosa();
exports.Mimosa_myuros = Mimosa_myuros;
Mimosa_myuros.specificEpithet = 'myuros';
Mimosa_myuros.stems = new v1_1.Stems();
Mimosa_myuros.stems.trichomes = new v1_1.Trichomes();
Mimosa_myuros.stems.trichomes.stellate = new Trichomes_1.Stellate();
Mimosa_myuros.stems.trichomes.stellate.subsessile = new Stellate_1.StellateSubsessile();
Mimosa_myuros.stems.trichomes.stellate.subsessile.are = 'present';
Mimosa_myuros.stems.trichomes.dendritic = new Trichomes_1.Dendritic();
Mimosa_myuros.stems.trichomes.dendritic.are = 'present';
Mimosa_myuros.stipule = new v1_1.Stipule();
Mimosa_myuros.stipule.margin = new Stipule_1.MarginStipule();
Mimosa_myuros.stipule.adaxial = new Stipule_1.AdaxialStipule();
Mimosa_myuros.stipule.abaxial = new Stipule_1.AbaxialStipule();
Mimosa_myuros.leaf = new v1_1.Leaf();
Mimosa_myuros.leaf.petiole = new Leaf_1.Petiole();
Mimosa_myuros.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_myuros.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_myuros.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_myuros.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_myuros.leaf.bipinnate.pinnae.setNumberOfPairsMinMax(5, 6);
Mimosa_myuros.leaf.bipinnate.pinnae.setNumberOfPairsRarelyMin(7);
Mimosa_myuros.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_myuros.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_myuros.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_myuros.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(5, 6);
Mimosa_myuros.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsRarelyMin(7);
Mimosa_myuros.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_myuros.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_myuros.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_myuros.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes = new v1_1.Trichomes();
Mimosa_myuros.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.fasciculate = new Trichomes_1.Fasciculate();
Mimosa_myuros.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.fasciculate.are = 'present';
Mimosa_myuros.inflorescence = new v1_1.Inflorescence();
Mimosa_myuros.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_myuros.inflorescence.spicate = new Inflorescence_1.Spicate();
Mimosa_myuros.flower = new v1_1.Flower();
Mimosa_myuros.flower.bracteole = new Flower_1.Bracteole();
Mimosa_myuros.flower.merism = '4-merous';
Mimosa_myuros.flower.numberWhorlsOfStamens = 'isostemonous';
Mimosa_myuros.flower.calyx = new Flower_1.Calyx();
Mimosa_myuros.flower.calyx.shape = 'campanulate';
Mimosa_myuros.flower.corolla = new Flower_1.Corolla();
Mimosa_myuros.flower.corolla.shape = 'campanulate';
Mimosa_myuros.androecium = new v1_1.Androecium();
Mimosa_myuros.androecium.filaments = new Androecium_1.Filaments();
Mimosa_myuros.androecium.filaments.colour = 'whitenish';
Mimosa_myuros.ginoecium = new v1_1.Ginoecium();
Mimosa_myuros.ginoecium.ovary = new Ginoecium_1.Ovary();
Mimosa_myuros.fruit = new v1_1.Fruit();
Mimosa_myuros.fruit.stipe = new Fruit_1.Stipe();
Mimosa_myuros.fruit.replum = new Fruit_1.Replum();
Mimosa_myuros.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_myuros.fruit.epicarp.trichomes = new v1_1.Trichomes();
Mimosa_myuros.fruit.epicarp.trichomes.verruciform = new Trichomes_1.Verruciform();
Mimosa_myuros.fruit.epicarp.trichomes.verruciform.are = 'present';
Mimosa_myuros.seed = new Seed_1.Seed();
// Description authorship
Mimosa_myuros.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_myuros.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source0 = new v1_2.Source();
source0.sourceType = 'article';
source0.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source0.year = 2018;
source0.title = 'Toward a Census of *Mimosa* (Leguminosae) in the Atlantic Domain, Southeastern Brazil';
source0.journal = 'Systematic Botany';
source0.volume = 43;
source0.number = 1;
source0.pages = 162 - 197;
Mimosa_myuros.addSource(source0);
/// Trichomes
var source1 = new v1_2.Source();
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source1.year = 2020;
source1.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source1.journal = 'Flora';
source1.number = 272;
source1.pages = 151702;
source1.figure = '5D';
source1.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_myuros.stems.trichomes.stellate.addSource(source1);
var source2 = new v1_2.Source();
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source2.year = 2020;
source2.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source2.journal = 'Flora';
source2.number = 272;
source2.pages = 151702;
source2.figure = '5H';
source2.obtainingMethod = 'stereoscope';
Mimosa_myuros.stems.trichomes.dendritic.addSource(source2);
var source3 = new v1_2.Source();
source3.sourceType = 'article';
source3.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source3.year = 2020;
source3.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source3.journal = 'Flora';
source3.number = 272;
source3.pages = 151702;
source3.figure = '5C';
source3.obtainingMethod = 'opticalMicroscope';
Mimosa_myuros.stems.trichomes.dendritic.addSource(source3);
var source4 = new v1_2.Source();
source4.sourceType = 'article';
source4.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source4.year = 2020;
source4.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source4.journal = 'Flora';
source4.number = 272;
source4.pages = 151702;
source4.figure = '7B';
source4.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_myuros.fruit.epicarp.trichomes.verruciform.addSource(source4);
