"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_aurivillus_var_calothamnos = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Capitate_1 = require("../../characters/v1/Trichomes/Capitate");
var Leaf_1 = require("../../characters/v1/Leaf");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
// Import annotation classes
var v1_2 = require("../../characters/v1");
var Stipule_1 = require("../../characters/v1/Stipule");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Androecium_1 = require("../../characters/v1/Androecium");
var Ginoecium_1 = require("../../characters/v1/Ginoecium");
var Fruit_1 = require("../../characters/v1/Fruit");
// Description of Mimosa aurivillus var. calothamnos
var Mimosa_aurivillus_var_calothamnos = new _1.Mimosa();
exports.Mimosa_aurivillus_var_calothamnos = Mimosa_aurivillus_var_calothamnos;
Mimosa_aurivillus_var_calothamnos.specificEpithet = 'aurivillus var. calothamnos';
Mimosa_aurivillus_var_calothamnos.stems = new v1_1.Stems();
Mimosa_aurivillus_var_calothamnos.stems.trichomes = new v1_1.Trichomes();
Mimosa_aurivillus_var_calothamnos.stems.trichomes.dendritic = new Trichomes_1.Dendritic();
Mimosa_aurivillus_var_calothamnos.stems.trichomes.dendritic.are = 'present';
Mimosa_aurivillus_var_calothamnos.stipule = new v1_1.Stipule();
Mimosa_aurivillus_var_calothamnos.stipule.margin = new Stipule_1.MarginStipule();
Mimosa_aurivillus_var_calothamnos.stipule.adaxial = new Stipule_1.AdaxialStipule();
Mimosa_aurivillus_var_calothamnos.stipule.abaxial = new Stipule_1.AbaxialStipule();
Mimosa_aurivillus_var_calothamnos.leaf = new v1_1.Leaf();
Mimosa_aurivillus_var_calothamnos.leaf.petiole = new Leaf_1.Petiole();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.setNumberOfPairsRarelyMin(1);
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.setNumberOfPairsMinMax(2, 5);
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(10, 21);
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes = new v1_1.Trichomes();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.fasciculate = new Trichomes_1.Fasciculate();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.fasciculate.are = 'present';
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.margin.trichomes = new v1_1.Trichomes();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.margin.trichomes.capitate = new Trichomes_1.Capitate();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.margin.trichomes.capitate.filiform = new Capitate_1.CapitateFiliform();
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.margin.trichomes.capitate.filiform.are = 'present';
Mimosa_aurivillus_var_calothamnos.inflorescence = new v1_1.Inflorescence();
Mimosa_aurivillus_var_calothamnos.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_aurivillus_var_calothamnos.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_aurivillus_var_calothamnos.flower = new v1_1.Flower();
Mimosa_aurivillus_var_calothamnos.flower.bracteole = new Flower_1.Bracteole();
Mimosa_aurivillus_var_calothamnos.flower.merism = '4-merous';
Mimosa_aurivillus_var_calothamnos.flower.numberWhorlsOfStamens = 'isostemonous';
Mimosa_aurivillus_var_calothamnos.flower.calyx = new Flower_1.Calyx();
Mimosa_aurivillus_var_calothamnos.flower.calyx.shape = 'campanulate';
Mimosa_aurivillus_var_calothamnos.flower.corolla = new Flower_1.Corolla();
Mimosa_aurivillus_var_calothamnos.flower.corolla.shape = 'campanulate';
Mimosa_aurivillus_var_calothamnos.androecium = new v1_1.Androecium();
Mimosa_aurivillus_var_calothamnos.androecium.filaments = new Androecium_1.Filaments();
Mimosa_aurivillus_var_calothamnos.androecium.filaments.colour = 'yellowish';
Mimosa_aurivillus_var_calothamnos.ginoecium = new v1_1.Ginoecium();
Mimosa_aurivillus_var_calothamnos.ginoecium.ovary = new Ginoecium_1.Ovary();
Mimosa_aurivillus_var_calothamnos.fruit = new v1_1.Fruit();
Mimosa_aurivillus_var_calothamnos.fruit.stipe = new Fruit_1.Stipe();
Mimosa_aurivillus_var_calothamnos.fruit.replum = new Fruit_1.Replum();
Mimosa_aurivillus_var_calothamnos.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_aurivillus_var_calothamnos.seed = new v1_1.Seed();
// Description authorship
Mimosa_aurivillus_var_calothamnos.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_aurivillus_var_calothamnos.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source0 = new v1_2.Source();
source0.sourceType = 'article';
source0.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source0.year = 2018;
source0.title = 'Toward a Census of *Mimosa* (Leguminosae) in the Atlantic Domain, Southeastern Brazil';
source0.journal = 'Systematic Botany';
source0.volume = 43;
source0.number = 1;
source0.pages = 162 - 197;
Mimosa_aurivillus_var_calothamnos.addSource(source0);
/// Trichomes
var source1 = new v1_2.Source();
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source1.year = 2020;
source1.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source1.journal = 'Flora';
source1.number = 272;
source1.pages = 151702;
source1.figure = '5E';
source1.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_aurivillus_var_calothamnos.stems.trichomes.dendritic.addSource(source1);
var source2 = new v1_2.Source();
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source2.year = 2020;
source2.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source2.journal = 'Flora';
source2.number = 272;
source2.pages = 151702;
source2.figure = '5I';
source2.obtainingMethod = 'opticalMicroscope';
Mimosa_aurivillus_var_calothamnos.stems.trichomes.dendritic.addSource(source2);
var source3 = new v1_2.Source();
source3.sourceType = 'article';
source3.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source3.year = 2020;
source3.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source3.journal = 'Flora';
source3.number = 272;
source3.pages = 151702;
source3.figure = '6E';
source3.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.fasciculate.addSource(source3);
var source4 = new v1_2.Source();
source4.sourceType = 'article';
source4.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source4.year = 2020;
source4.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source4.journal = 'Flora';
source4.number = 272;
source4.pages = 151702;
source4.figure = '8D';
source4.obtainingMethod = 'opticalMicroscope';
Mimosa_aurivillus_var_calothamnos.leaf.bipinnate.pinnae.leaflet.margin.trichomes.capitate.filiform.addSource(source4);
