"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_schomburgkii = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Stellate_1 = require("../../characters/v1/Trichomes/Stellate");
var Leaf_1 = require("../../characters/v1/Leaf");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Flower_1 = require("../../characters/v1/Flower");
var Fruit_1 = require("../../characters/v1/Fruit");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Stipule_1 = require("../../characters/v1/Stipule");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Androecium_1 = require("../../characters/v1/Androecium");
// Import annotation classes
var v1_2 = require("../../characters/v1");
// Description of Mimosa schomburgkii
var Mimosa_schomburgkii = new _1.Mimosa();
exports.Mimosa_schomburgkii = Mimosa_schomburgkii;
Mimosa_schomburgkii.specificEpithet = 'schomburgkii';
Mimosa_schomburgkii.habit = 'tree';
Mimosa_schomburgkii.prickles = new v1_1.Prickles();
Mimosa_schomburgkii.prickles.are = 'absent';
Mimosa_schomburgkii.trichomes = new v1_1.Trichomes();
Mimosa_schomburgkii.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_schomburgkii.trichomes.filiform.are = 'present';
Mimosa_schomburgkii.trichomes.stellate = new Trichomes_1.Stellate();
Mimosa_schomburgkii.trichomes.stellate.are = 'present';
Mimosa_schomburgkii.trichomes.stellate.subsessile = new Stellate_1.StellateSubsessile();
Mimosa_schomburgkii.trichomes.stellate.subsessile.are = 'present';
Mimosa_schomburgkii.trichomes.granular = new Trichomes_1.Granular();
Mimosa_schomburgkii.trichomes.granular.are = 'present';
Mimosa_schomburgkii.stipule = new v1_1.Stipule();
Mimosa_schomburgkii.stipule.margin = new Stipule_1.MarginStipule();
Mimosa_schomburgkii.stipule.adaxial = new Stipule_1.AdaxialStipule();
Mimosa_schomburgkii.stipule.abaxial = new Stipule_1.AbaxialStipule();
Mimosa_schomburgkii.leaf = new v1_1.Leaf();
Mimosa_schomburgkii.leaf.petiole = new Leaf_1.Petiole();
Mimosa_schomburgkii.leaf.petiole.present = true;
Mimosa_schomburgkii.leaf.petiole.setLength(3);
Mimosa_schomburgkii.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_schomburgkii.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_schomburgkii.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_schomburgkii.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.setNumberOfPairsMinMax(7, 12);
Mimosa_schomburgkii.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.paraphillidia.are = 'present';
Mimosa_schomburgkii.leaf.bipinnate.pinnae.paraphillidia.setLength(null);
Mimosa_schomburgkii.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(15, 29);
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes = new v1_1.Trichomes();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.stellate = new Trichomes_1.Stellate();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.stellate.subsessile = new Stellate_1.StellateSubsessile();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.stellate.subsessile.are = 'present';
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.stellate.stalked = new Stellate_1.StellateStalked();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.stellate.stalked.are = 'present or absent';
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.peltate = new Trichomes_1.Peltate();
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.peltate.are = 'present';
Mimosa_schomburgkii.inflorescence = new v1_1.Inflorescence();
Mimosa_schomburgkii.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_schomburgkii.inflorescence.spicate = new Inflorescence_1.Spicate();
Mimosa_schomburgkii.flower = new v1_1.Flower();
Mimosa_schomburgkii.flower.merism = '4-merous';
Mimosa_schomburgkii.flower.numberWhorlsOfStamens = 'diplostemonous';
Mimosa_schomburgkii.flower.bracteole = new Flower_1.Bracteole();
Mimosa_schomburgkii.flower.calyx = new Flower_1.Calyx();
Mimosa_schomburgkii.flower.calyx.numSepals = 3;
Mimosa_schomburgkii.flower.calyx.setLengthMinMax(1, 2);
Mimosa_schomburgkii.flower.calyx.shape = 'campanulate';
Mimosa_schomburgkii.flower.corolla = new Flower_1.Corolla();
Mimosa_schomburgkii.flower.corolla.numPepals = 3;
Mimosa_schomburgkii.flower.corolla.setLengthMinMax(2, 3);
Mimosa_schomburgkii.flower.corolla.shape = 'campanulate';
Mimosa_schomburgkii.flower.corolla.trichomes = new v1_1.Trichomes();
Mimosa_schomburgkii.flower.corolla.trichomes.stellate = new Trichomes_1.Stellate();
Mimosa_schomburgkii.flower.corolla.trichomes.stellate.lepidote = new Stellate_1.StellateLepidote();
Mimosa_schomburgkii.flower.corolla.trichomes.stellate.lepidote.are = 'present';
Mimosa_schomburgkii.androecium = new v1_1.Androecium();
Mimosa_schomburgkii.androecium.filaments = new Androecium_1.Filaments();
Mimosa_schomburgkii.androecium.filaments.colour = 'whitenish';
Mimosa_schomburgkii.fruit = new v1_1.Fruit();
Mimosa_schomburgkii.fruit.replum = new Fruit_1.Replum();
Mimosa_schomburgkii.fruit.replum.shape = 'straight';
Mimosa_schomburgkii.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_schomburgkii.fruit.epicarp.type = 'monospermic';
Mimosa_schomburgkii.fruit.epicarp.margin = 'straight';
Mimosa_schomburgkii.fruit.epicarp.trichomes = new v1_1.Trichomes();
Mimosa_schomburgkii.fruit.epicarp.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_schomburgkii.fruit.epicarp.trichomes.filiform.are = 'present';
// Description authorship
Mimosa_schomburgkii.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_schomburgkii.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source0 = new v1_2.Source();
source0.sourceType = 'article';
source0.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source0.year = 2018;
source0.title = 'Toward a Census of *Mimosa* (Leguminosae) in the Atlantic Domain, Southeastern Brazil';
source0.journal = 'Systematic Botany';
source0.volume = 43;
source0.number = 1;
source0.pages = 162 - 197;
Mimosa_schomburgkii.addSource(source0);
/// Trichomes
var source1 = new v1_2.Source();
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source1.year = 2020;
source1.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source1.journal = 'Flora';
source1.number = 272;
source1.pages = 151702;
source1.figure = '4D';
source1.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.stellate.subsessile.addSource(source1);
var source2 = new v1_2.Source();
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source2.year = 2020;
source2.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source2.journal = 'Flora';
source2.number = 272;
source2.pages = 151702;
source2.figure = '4E';
source2.obtainingMethod = 'opticalMicroscope';
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.stellate.subsessile.addSource(source2);
var source3 = new v1_2.Source();
source3.sourceType = 'article';
source3.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source3.year = 2020;
source3.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source3.journal = 'Flora';
source3.number = 272;
source3.pages = 151702;
source3.figure = '4F';
source3.obtainingMethod = 'opticalMicroscope';
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.stellate.stalked.addSource(source3);
var source4 = new v1_2.Source();
source4.sourceType = 'article';
source4.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source4.year = 2020;
source4.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source4.journal = 'Flora';
source4.number = 272;
source4.pages = 151702;
source4.figure = '4G';
source4.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.stellate.stalked.addSource(source4);
var source5 = new v1_2.Source();
source5.sourceType = 'article';
source5.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source5.year = 2020;
source5.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source5.journal = 'Flora';
source5.number = 272;
source5.pages = 151702;
source5.figure = '4H';
source5.obtainingMethod = 'opticalMicroscope';
Mimosa_schomburgkii.flower.corolla.trichomes.stellate.lepidote.addSource(source5);
var source6 = new v1_2.Source();
source6.sourceType = 'article';
source6.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source6.year = 2020;
source6.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source6.journal = 'Flora';
source6.number = 272;
source6.pages = 151702;
source6.figure = '4I';
source6.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_schomburgkii.flower.corolla.trichomes.stellate.lepidote.addSource(source6);
var source7 = new v1_2.Source();
source7.sourceType = 'article';
source7.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source7.year = 2020;
source7.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source7.journal = 'Flora';
source7.number = 272;
source7.pages = 151702;
source7.figure = '9M';
source7.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.peltate.addSource(source7);
var source8 = new v1_2.Source();
source8.sourceType = 'article';
source8.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source8.year = 2020;
source8.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source8.journal = 'Flora';
source8.number = 272;
source8.pages = 151702;
source8.figure = '9N';
source8.obtainingMethod = 'stereoscope';
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.peltate.addSource(source8);
Mimosa_schomburgkii.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.stellate.subsessile.addSource(source8);
