"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_sevilhae = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Leaf_1 = require("../../characters/v1/Leaf");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Paraphillidia_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Paraphillidia");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Androecium_1 = require("../../characters/v1/Androecium");
var Filaments_1 = require("../../characters/v1/Androecium/Filaments");
var baseFilaments_1 = require("../../characters/v1/Androecium/Filaments/baseFilaments");
var Fruit_1 = require("../../characters/v1/Fruit");
// Import annotation classes
var v1_2 = require("../../characters/v1");
// Description of Mimosa sevilhae
var Mimosa_sevilhae = new _1.Mimosa();
exports.Mimosa_sevilhae = Mimosa_sevilhae;
Mimosa_sevilhae.specificEpithet = 'sevilhae';
Mimosa_sevilhae.habit = ['herb', 'subshrub'];
Mimosa_sevilhae.stems = new v1_1.Stems();
Mimosa_sevilhae.stems.orientation = 'decumbent';
Mimosa_sevilhae.stems.shape = 'cylindric';
Mimosa_sevilhae.stems.prickles = new v1_1.Prickles();
Mimosa_sevilhae.stems.prickles.are = 'present';
Mimosa_sevilhae.stems.prickles.frequency = 'serially armed';
Mimosa_sevilhae.stems.prickles.orientation = 'decurved';
Mimosa_sevilhae.stems.prickles.setLengthMinMax(1, 1.5);
Mimosa_sevilhae.stipule = new v1_1.Stipule();
Mimosa_sevilhae.stipule.setLengthMinMax(1.1, 2);
Mimosa_sevilhae.stipule.shape = 'lanceolate';
Mimosa_sevilhae.stipule.nervation = '1-nerved';
Mimosa_sevilhae.stipule.persistance = 'persistent';
Mimosa_sevilhae.leaf = new v1_1.Leaf();
Mimosa_sevilhae.leaf.petiole = new Leaf_1.Petiole();
Mimosa_sevilhae.leaf.petiole.setLengthMinMax(10, 23);
Mimosa_sevilhae.leaf.petiole.flattening = 'not dorsiventrally flattened';
Mimosa_sevilhae.leaf.petiole.transversalShape = ['4-ribbed', '4-gonal'];
Mimosa_sevilhae.leaf.petiole.persistance = 'caducous';
Mimosa_sevilhae.leaf.petiole.prickles = new v1_1.Prickles();
Mimosa_sevilhae.leaf.petiole.prickles.are = 'present';
Mimosa_sevilhae.leaf.petiole.prickles.frequency = 'sparsely armed';
Mimosa_sevilhae.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_sevilhae.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_sevilhae.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_sevilhae.leaf.bipinnate.rachis.setLengthMinMax(3, 9);
Mimosa_sevilhae.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_sevilhae.leaf.bipinnate.rachis.spicule.is = 'present or absent';
Mimosa_sevilhae.leaf.bipinnate.rachis.spicule.setLengthMinMax(0.3, 0.6);
Mimosa_sevilhae.leaf.bipinnate.rachis.spicule.shape = 'linear-subulate';
Mimosa_sevilhae.leaf.bipinnate.rachis.prickles = new v1_1.Prickles();
Mimosa_sevilhae.leaf.bipinnate.rachis.prickles.are = 'present';
Mimosa_sevilhae.leaf.bipinnate.rachis.prickles.frequency = 'sparsely armed';
Mimosa_sevilhae.leaf.bipinnate.pinnae.setNumberOfPairsRarelyMin(1);
Mimosa_sevilhae.leaf.bipinnate.pinnae.setNumberOfPairs(2);
Mimosa_sevilhae.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_sevilhae.leaf.bipinnate.pinnae.paraphillidia.are = 'present';
Mimosa_sevilhae.leaf.bipinnate.pinnae.paraphillidia.setLengthMinMax(0.15, 0.2);
Mimosa_sevilhae.leaf.bipinnate.pinnae.paraphillidia.shape = 'short-triangular';
Mimosa_sevilhae.leaf.bipinnate.pinnae.paraphillidia.distanceFromFirstPairOfLeaflets = new Paraphillidia_1.DistanceFromFirstPairOfLeaflets();
Mimosa_sevilhae.leaf.bipinnate.pinnae.paraphillidia.distanceFromFirstPairOfLeaflets.setLengthMinMax(1.2, 2);
Mimosa_sevilhae.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_sevilhae.leaf.bipinnate.pinnae.rachilla.setLengthMinMax(6.5, 14.5);
Mimosa_sevilhae.leaf.bipinnate.pinnae.rachilla.trichomes = new v1_1.Trichomes();
Mimosa_sevilhae.leaf.bipinnate.pinnae.rachilla.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_sevilhae.leaf.bipinnate.pinnae.rachilla.trichomes.filiform.are = 'present';
Mimosa_sevilhae.leaf.bipinnate.pinnae.rachilla.trichomes.filiform.density = 'sparsely';
Mimosa_sevilhae.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_sevilhae.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(5, 9);
Mimosa_sevilhae.leaf.bipinnate.pinnae.leaflet.setHeightMinMax(3.5, 7.6);
Mimosa_sevilhae.leaf.bipinnate.pinnae.leaflet.setWidthMinMax(1.4, 2);
Mimosa_sevilhae.leaf.bipinnate.pinnae.leaflet.shape = 'oblong';
Mimosa_sevilhae.leaf.bipinnate.pinnae.leaflet.base = ['oblique-rounded', 'oblique-truncate', 'oblique-acute'];
Mimosa_sevilhae.leaf.bipinnate.pinnae.leaflet.apex = ['obtuse-mucronulate', 'rounded-mucronulate'];
Mimosa_sevilhae.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_sevilhae.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_sevilhae.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_sevilhae.inflorescence = new v1_1.Inflorescence();
Mimosa_sevilhae.inflorescence.type = 'racemose';
Mimosa_sevilhae.inflorescence.shape = 'moriform';
Mimosa_sevilhae.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_sevilhae.inflorescence.peduncle.setLengthMinMax(13, 17.5);
Mimosa_sevilhae.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_sevilhae.inflorescence.capitate.setLengthMinMax(2.5, 3.5);
Mimosa_sevilhae.inflorescence.capitate.shape = 'globose';
Mimosa_sevilhae.flower = new v1_1.Flower();
Mimosa_sevilhae.flower.bracteole = new Flower_1.Bracteole();
Mimosa_sevilhae.flower.bracteole.setLengthMinMax(0.6, 1);
Mimosa_sevilhae.flower.bracteole.shape = 'spatulate';
Mimosa_sevilhae.flower.bracteole.trichomes = new v1_1.Trichomes();
Mimosa_sevilhae.flower.bracteole.trichomes.granular = new Trichomes_1.Granular();
Mimosa_sevilhae.flower.bracteole.trichomes.granular.are = 'present or absent';
Mimosa_sevilhae.flower.merism = '4-merous';
Mimosa_sevilhae.flower.calyx = new Flower_1.Calyx();
Mimosa_sevilhae.flower.calyx.setLengthMinMax(0.35, 0.45);
Mimosa_sevilhae.flower.calyx.shape = 'campanulate';
Mimosa_sevilhae.flower.calyx.apex = 'shortly denticulate';
Mimosa_sevilhae.flower.corolla = new Flower_1.Corolla();
Mimosa_sevilhae.flower.corolla.setLengthMinMax(1.5, 2);
Mimosa_sevilhae.flower.corolla.shape = ['campanulate', 'turbinate'];
Mimosa_sevilhae.androecium = new v1_1.Androecium();
Mimosa_sevilhae.androecium.filaments = new Androecium_1.Filaments();
Mimosa_sevilhae.androecium.filaments.setLengthMinMax(4.5, 5);
Mimosa_sevilhae.androecium.filaments.colour = 'pinkish';
Mimosa_sevilhae.androecium.filaments.base = new Filaments_1.baseFilaments();
Mimosa_sevilhae.androecium.filaments.base.connation = new baseFilaments_1.ConnationOfFilamentsAtBase();
Mimosa_sevilhae.androecium.filaments.base.connation.setLength(0.2);
Mimosa_sevilhae.fruit = new v1_1.Fruit();
Mimosa_sevilhae.fruit.setHeightMinMax(20, 27);
Mimosa_sevilhae.fruit.setWidthMinMax(5, 5.5);
Mimosa_sevilhae.fruit.stipe = new Fruit_1.Stipe();
Mimosa_sevilhae.fruit.stipe.is = 'absent';
Mimosa_sevilhae.fruit.shape = 'oblong';
Mimosa_sevilhae.fruit.curvature = 'straight';
Mimosa_sevilhae.fruit.replum = new Fruit_1.Replum();
Mimosa_sevilhae.fruit.replum.shape = 'straight';
Mimosa_sevilhae.fruit.replum.prickles = new v1_1.Prickles();
Mimosa_sevilhae.fruit.replum.prickles.are = 'present';
Mimosa_sevilhae.fruit.replum.prickles.frequency = 'densely armed';
Mimosa_sevilhae.fruit.replum.prickles.orientation = 'decurved';
Mimosa_sevilhae.fruit.replum.trichomes = new v1_1.Trichomes();
Mimosa_sevilhae.fruit.replum.trichomes.granular = new Trichomes_1.Granular();
Mimosa_sevilhae.fruit.replum.trichomes.granular.are = 'present';
Mimosa_sevilhae.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_sevilhae.fruit.epicarp.prickles = new v1_1.Prickles();
Mimosa_sevilhae.fruit.epicarp.prickles.are = 'present';
Mimosa_sevilhae.fruit.epicarp.prickles.orientation = 'decurved';
Mimosa_sevilhae.fruit.epicarp.trichomes = new v1_1.Trichomes();
Mimosa_sevilhae.fruit.epicarp.trichomes.granular = new Trichomes_1.Granular();
Mimosa_sevilhae.fruit.epicarp.trichomes.granular.are = 'present';
Mimosa_sevilhae.fruit.setNumberOfSeedsMinMax(6, 9);
Mimosa_sevilhae.seed = new v1_1.Seed();
Mimosa_sevilhae.seed.setHeightMinMax(3, 3.2);
Mimosa_sevilhae.seed.setWidthMinMax(1.9, 2.1);
Mimosa_sevilhae.seed.shape = 'obovate';
Mimosa_sevilhae.seed.pleurogram = 'median';
// Description authorship
Mimosa_sevilhae.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_sevilhae.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source1 = new v1_2.Source();
source1.obraPrinceps = 'yes';
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. and Morim, M.P. and Simon, M.F., Dutra, V.F. and Baumgratz, J.F.A.';
source1.year = 2021;
source1.title = 'New Species of *Mimosa* (Leguminosae) from Brazil';
source1.journal = 'Systematic Botany';
source1.volume = 46;
source1.number = 2;
source1.pages = 339 - 351;
Mimosa_sevilhae.addSource(source1);
var source2 = new v1_2.Source();
source2.obraPrinceps = 'yes';
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. and Morim, M.P. and Simon, M.F., Dutra, V.F. and Baumgratz, J.F.A.';
source2.year = 2021;
source2.title = 'New Species of *Mimosa* (Leguminosae) from Brazil';
source2.journal = 'Systematic Botany';
source2.volume = 46;
source2.number = 2;
source2.pages = 339 - 351;
source2.figure = '8';
source2.obtainingMethod = 'drawing';
Mimosa_sevilhae.addSource(source2);
