"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_furfuracea = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Stellate_1 = require("../../characters/v1/Trichomes/Stellate");
var Leaf_1 = require("../../characters/v1/Leaf");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Stipule_1 = require("../../characters/v1/Stipule");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Fruit_1 = require("../../characters/v1/Fruit");
var Androecium_1 = require("../../characters/v1/Androecium");
var Ginoecium_1 = require("../../characters/v1/Ginoecium");
var Seed_1 = require("../../characters/v1/Seed");
// Import annotation classes
var v1_2 = require("../../characters/v1");
// Description of Mimosa furfuracea
var Mimosa_furfuracea = new _1.Mimosa();
exports.Mimosa_furfuracea = Mimosa_furfuracea;
Mimosa_furfuracea.specificEpithet = 'furfuracea';
Mimosa_furfuracea.stems = new v1_1.Stems();
Mimosa_furfuracea.stems.trichomes = new v1_1.Trichomes();
Mimosa_furfuracea.stems.trichomes.dendritic = new Trichomes_1.Dendritic();
Mimosa_furfuracea.stems.trichomes.dendritic.are = 'present';
Mimosa_furfuracea.stipule = new v1_1.Stipule();
Mimosa_furfuracea.stipule.margin = new Stipule_1.MarginStipule();
Mimosa_furfuracea.stipule.adaxial = new Stipule_1.AdaxialStipule();
Mimosa_furfuracea.stipule.abaxial = new Stipule_1.AbaxialStipule();
Mimosa_furfuracea.leaf = new v1_1.Leaf();
Mimosa_furfuracea.leaf.petiole = new Leaf_1.Petiole();
Mimosa_furfuracea.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_furfuracea.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_furfuracea.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_furfuracea.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_furfuracea.leaf.bipinnate.pinnae.setNumberOfPairsMinMax(2, 3);
Mimosa_furfuracea.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_furfuracea.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_furfuracea.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_furfuracea.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsRarelyMin(6);
Mimosa_furfuracea.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(9, 16);
Mimosa_furfuracea.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_furfuracea.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_furfuracea.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_furfuracea.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes = new v1_1.Trichomes();
Mimosa_furfuracea.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.fasciculate = new Trichomes_1.Fasciculate();
Mimosa_furfuracea.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.fasciculate.are = 'present';
Mimosa_furfuracea.inflorescence = new v1_1.Inflorescence();
Mimosa_furfuracea.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_furfuracea.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_furfuracea.flower = new v1_1.Flower();
Mimosa_furfuracea.flower.bracteole = new Flower_1.Bracteole();
Mimosa_furfuracea.flower.merism = '4-merous';
Mimosa_furfuracea.flower.numberWhorlsOfStamens = 'isostemonous';
Mimosa_furfuracea.flower.calyx = new Flower_1.Calyx();
Mimosa_furfuracea.flower.calyx.shape = 'pateliform';
Mimosa_furfuracea.flower.corolla = new Flower_1.Corolla();
Mimosa_furfuracea.flower.corolla.shape = 'campanulate';
Mimosa_furfuracea.flower.corolla.trichomes = new v1_1.Trichomes();
Mimosa_furfuracea.flower.corolla.trichomes.stellate = new Trichomes_1.Stellate();
Mimosa_furfuracea.flower.corolla.trichomes.stellate.lepidote = new Stellate_1.StellateLepidote();
Mimosa_furfuracea.flower.corolla.trichomes.stellate.lepidote.are = 'present';
Mimosa_furfuracea.androecium = new v1_1.Androecium();
Mimosa_furfuracea.androecium.filaments = new Androecium_1.Filaments();
Mimosa_furfuracea.androecium.filaments.colour = 'yellowish';
Mimosa_furfuracea.ginoecium = new v1_1.Ginoecium();
Mimosa_furfuracea.ginoecium.ovary = new Ginoecium_1.Ovary();
Mimosa_furfuracea.fruit = new v1_1.Fruit();
Mimosa_furfuracea.fruit.stipe = new Fruit_1.Stipe();
Mimosa_furfuracea.fruit.replum = new Fruit_1.Replum();
Mimosa_furfuracea.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_furfuracea.seed = new Seed_1.Seed();
// Description authorship
Mimosa_furfuracea.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_furfuracea.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source0 = new v1_2.Source();
source0.sourceType = 'article';
source0.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source0.year = 2018;
source0.title = 'Toward a Census of *Mimosa* (Leguminosae) in the Atlantic Domain, Southeastern Brazil';
source0.journal = 'Systematic Botany';
source0.volume = 43;
source0.number = 1;
source0.pages = 162 - 197;
Mimosa_furfuracea.addSource(source0);
/// Trichomes
var source1 = new v1_2.Source();
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source1.year = 2020;
source1.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source1.journal = 'Flora';
source1.number = 272;
source1.pages = 151702;
source1.figure = '4H';
source1.obtainingMethod = 'opticalMicroscope';
Mimosa_furfuracea.flower.corolla.trichomes.stellate.lepidote.addSource(source1);
var source2 = new v1_2.Source();
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source2.year = 2020;
source2.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source2.journal = 'Flora';
source2.number = 272;
source2.pages = 151702;
source2.figure = '5A,B';
source2.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_furfuracea.stems.trichomes.dendritic.addSource(source2);
var source3 = new v1_2.Source();
source3.sourceType = 'article';
source3.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source3.year = 2020;
source3.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source3.journal = 'Flora';
source3.number = 272;
source3.pages = 151702;
source3.figure = '5J';
source3.obtainingMethod = 'stereoscope';
Mimosa_furfuracea.stems.trichomes.dendritic.addSource(source3);
var source4 = new v1_2.Source();
source4.sourceType = 'article';
source4.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source4.year = 2020;
source4.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source4.journal = 'Flora';
source4.number = 272;
source4.pages = 151702;
source4.figure = '6D';
source4.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_furfuracea.stems.trichomes.dendritic.addSource(source4);
var source5 = new v1_2.Source();
source5.sourceType = 'article';
source5.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source5.year = 2020;
source5.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source5.journal = 'Flora';
source5.number = 272;
source5.pages = 151702;
source5.figure = '6F';
source5.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_furfuracea.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.fasciculate.addSource(source5);
