"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_paludosa = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Capitate_1 = require("../../characters/v1/Trichomes/Capitate");
var Leaf_1 = require("../../characters/v1/Leaf");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Stipule_1 = require("../../characters/v1/Stipule");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Flower_1 = require("../../characters/v1/Flower");
var Fruit_1 = require("../../characters/v1/Fruit");
var Androecium_1 = require("../../characters/v1/Androecium");
var Ginoecium_1 = require("../../characters/v1/Ginoecium");
var Seed_1 = require("../../characters/v1/Seed");
// Import annotation classes
var v1_2 = require("../../characters/v1");
// Description of Mimosa paludosa
var Mimosa_paludosa = new _1.Mimosa();
exports.Mimosa_paludosa = Mimosa_paludosa;
Mimosa_paludosa.specificEpithet = 'paludosa';
Mimosa_paludosa.stems = new v1_1.Stems();
Mimosa_paludosa.stems.trichomes = new v1_1.Trichomes();
Mimosa_paludosa.stems.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_paludosa.stems.trichomes.filiform.are = 'present';
Mimosa_paludosa.stems.trichomes.setiform = new Trichomes_1.Setiform();
Mimosa_paludosa.stems.trichomes.setiform.are = 'present';
Mimosa_paludosa.stems.trichomes.capitate = new Trichomes_1.Capitate();
Mimosa_paludosa.stems.trichomes.capitate.setiform = new Capitate_1.CapitateSetiform();
Mimosa_paludosa.stems.trichomes.capitate.setiform.are = 'present';
Mimosa_paludosa.stipule = new v1_1.Stipule();
Mimosa_paludosa.stipule.margin = new Stipule_1.MarginStipule();
Mimosa_paludosa.stipule.adaxial = new Stipule_1.AdaxialStipule();
Mimosa_paludosa.stipule.abaxial = new Stipule_1.AbaxialStipule();
Mimosa_paludosa.leaf = new v1_1.Leaf();
Mimosa_paludosa.leaf.petiole = new Leaf_1.Petiole();
Mimosa_paludosa.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_paludosa.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_paludosa.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_paludosa.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_paludosa.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_paludosa.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_paludosa.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_paludosa.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(7, 17);
Mimosa_paludosa.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_paludosa.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_paludosa.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_paludosa.inflorescence = new v1_1.Inflorescence();
Mimosa_paludosa.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_paludosa.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_paludosa.flower = new v1_1.Flower();
Mimosa_paludosa.flower.bracteole = new Flower_1.Bracteole();
Mimosa_paludosa.flower.merism = '4-merous';
Mimosa_paludosa.flower.numberWhorlsOfStamens = 'diplostemonous';
Mimosa_paludosa.flower.calyx = new Flower_1.Calyx();
Mimosa_paludosa.flower.calyx.shape = 'campanulate';
Mimosa_paludosa.flower.corolla = new Flower_1.Corolla();
Mimosa_paludosa.flower.corolla.shape = 'campanulate';
Mimosa_paludosa.androecium = new v1_1.Androecium();
Mimosa_paludosa.androecium.filaments = new Androecium_1.Filaments();
Mimosa_paludosa.androecium.filaments.colour = 'pinkish';
Mimosa_paludosa.ginoecium = new v1_1.Ginoecium();
Mimosa_paludosa.ginoecium.ovary = new Ginoecium_1.Ovary();
Mimosa_paludosa.fruit = new v1_1.Fruit();
Mimosa_paludosa.fruit.stipe = new Fruit_1.Stipe();
Mimosa_paludosa.fruit.replum = new Fruit_1.Replum();
Mimosa_paludosa.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_paludosa.seed = new Seed_1.Seed();
// Description authorship
Mimosa_paludosa.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_paludosa.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source0 = new v1_2.Source();
source0.sourceType = 'article';
source0.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source0.year = 2018;
source0.title = 'Toward a Census of *Mimosa* (Leguminosae) in the Atlantic Domain, Southeastern Brazil';
source0.journal = 'Systematic Botany';
source0.volume = 43;
source0.number = 1;
source0.pages = 162 - 197;
Mimosa_paludosa.addSource(source0);
/// Trichomes
var source1 = new v1_2.Source();
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source1.year = 2020;
source1.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source1.journal = 'Flora';
source1.number = 272;
source1.pages = 151702;
source1.figure = '1A';
source1.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_paludosa.stems.trichomes.filiform.addSource(source1);
var source2 = new v1_2.Source();
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source2.year = 2020;
source2.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source2.journal = 'Flora';
source2.number = 272;
source2.pages = 151702;
source2.figure = '9C';
source2.obtainingMethod = 'scanningElectronMicroscope';
Mimosa_paludosa.stems.trichomes.filiform.addSource(source2);
Mimosa_paludosa.stems.trichomes.capitate.setiform.addSource(source2);
var source3 = new v1_2.Source();
source3.sourceType = 'article';
source3.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source3.year = 2020;
source3.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source3.journal = 'Flora';
source3.number = 272;
source3.pages = 151702;
source3.figure = '9D';
source3.obtainingMethod = 'photo';
Mimosa_paludosa.stems.trichomes.capitate.setiform.addSource(source3);
var source4 = new v1_2.Source();
source4.sourceType = 'article';
source4.authorship = 'Jordão, L.S.B. & Morim, M.P. & Baumgratz, J.F.A.';
source4.year = 2020;
source4.title = 'Trichomes in *Mimosa* (Leguminosae): Towards a characterization and a terminology standardization';
source4.journal = 'Flora';
source4.number = 272;
source4.pages = 151702;
source4.figure = '9E';
source4.obtainingMethod = 'opticalMicroscope';
Mimosa_paludosa.stems.trichomes.capitate.setiform.addSource(source4);
