"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Mimosa_afranioi = void 0;
// Import genus Mimosa
var _1 = require(".");
// Import characters
var v1_1 = require("../../characters/v1");
var Trichomes_1 = require("../../characters/v1/Trichomes");
var Leaf_1 = require("../../characters/v1/Leaf");
var Stipule_1 = require("../../characters/v1/Stipule");
var Spicule_1 = require("../../characters/v1/Leaf/Bipinnate/Rachis/Spicule");
var Bipinnate_1 = require("../../characters/v1/Leaf/Bipinnate");
var Pinnae_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae");
var Paraphillidia_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Paraphillidia");
var Leaflet_1 = require("../../characters/v1/Leaf/Bipinnate/Pinnae/Leaflet");
var Flower_1 = require("../../characters/v1/Flower");
var Fruit_1 = require("../../characters/v1/Fruit");
var Inflorescence_1 = require("../../characters/v1/Inflorescence");
var Bracteole_1 = require("../../characters/v1/Flower/Bracteole");
var Corolla_1 = require("../../characters/v1/Flower/Corolla");
var Lobes_1 = require("../../characters/v1/Flower/Corolla/Lobes");
var Androecium_1 = require("../../characters/v1/Androecium");
var Filaments_1 = require("../../characters/v1/Androecium/Filaments");
var baseFilaments_1 = require("../../characters/v1/Androecium/Filaments/baseFilaments");
// Import annotation classes
var v1_2 = require("../../characters/v1");
// Description of Mimosa afranioi
var Mimosa_afranioi = new _1.Mimosa();
exports.Mimosa_afranioi = Mimosa_afranioi;
Mimosa_afranioi.specificEpithet = 'afranioi';
Mimosa_afranioi.habit = ['herb', 'subshrub'];
Mimosa_afranioi.stems = new v1_1.Stems();
Mimosa_afranioi.stems.length = 2;
Mimosa_afranioi.stems.orientation = ['procumbent', 'scandent'];
Mimosa_afranioi.stems.shape = '5-gonal';
Mimosa_afranioi.stems.prickles = new v1_1.Prickles();
Mimosa_afranioi.stems.prickles.are = 'present';
Mimosa_afranioi.stems.prickles.setLengthMinMax(0.4, 2.1);
Mimosa_afranioi.stems.prickles.orientation = 'decurved';
Mimosa_afranioi.stems.prickles.persistance = 'caducous';
Mimosa_afranioi.stems.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.stems.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.stems.trichomes.filiform.are = 'present';
Mimosa_afranioi.stems.trichomes.granular = new Trichomes_1.Granular();
Mimosa_afranioi.stems.trichomes.granular.are = 'present';
Mimosa_afranioi.stipule = new v1_1.Stipule();
Mimosa_afranioi.stipule.shape = 'lanceolate';
Mimosa_afranioi.stipule.setLengthMinMax(2.1, 5.5);
Mimosa_afranioi.stipule.nervation = '1-nerved';
Mimosa_afranioi.stipule.persistance = 'persistent';
Mimosa_afranioi.stipule.abaxial = new Stipule_1.AbaxialStipule();
Mimosa_afranioi.stipule.abaxial.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.stipule.abaxial.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.stipule.abaxial.trichomes.filiform.are = 'present';
Mimosa_afranioi.stipule.abaxial.trichomes.granular = new Trichomes_1.Granular();
Mimosa_afranioi.stipule.abaxial.trichomes.granular.are = 'present';
Mimosa_afranioi.stipule.margin = new Stipule_1.MarginStipule();
Mimosa_afranioi.stipule.margin.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.stipule.margin.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.stipule.margin.trichomes.filiform.are = 'present';
Mimosa_afranioi.stipule.margin.trichomes.granular = new Trichomes_1.Granular();
Mimosa_afranioi.stipule.margin.trichomes.granular.are = 'present';
Mimosa_afranioi.leaf = new v1_1.Leaf();
Mimosa_afranioi.leaf.phyllotaxis = 'distichous';
Mimosa_afranioi.leaf.petiole = new Leaf_1.Petiole();
Mimosa_afranioi.leaf.petiole.setLengthMinMax(6, 37);
Mimosa_afranioi.leaf.petiole.flattening = ['slightly dorsiventrally flattened', 'not dorsiventrally flattened'];
Mimosa_afranioi.leaf.petiole.persistance = 'caducous';
Mimosa_afranioi.leaf.petiole.prickles = new v1_1.Prickles();
Mimosa_afranioi.leaf.petiole.prickles.are = 'present';
Mimosa_afranioi.leaf.bipinnate = new Leaf_1.Bipinnate();
Mimosa_afranioi.leaf.bipinnate.rachis = new Bipinnate_1.Rachis();
Mimosa_afranioi.leaf.bipinnate.rachis.setLengthMinMax(7, 40);
Mimosa_afranioi.leaf.bipinnate.rachis.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.leaf.bipinnate.rachis.trichomes.are = 'present or absent';
Mimosa_afranioi.leaf.bipinnate.rachis.spicule = new Spicule_1.Spicule();
Mimosa_afranioi.leaf.bipinnate.rachis.spicule.is = 'present or absent';
Mimosa_afranioi.leaf.bipinnate.rachis.spicule.setLength(0.1);
Mimosa_afranioi.leaf.bipinnate.rachis.spicule.shape = 'deltate';
Mimosa_afranioi.leaf.bipinnate.rachis.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.leaf.bipinnate.rachis.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.leaf.bipinnate.rachis.trichomes.filiform.are = 'present or absent';
Mimosa_afranioi.leaf.bipinnate.pinnae = new Bipinnate_1.Pinnae();
Mimosa_afranioi.leaf.bipinnate.pinnae.setNumberOfPairsRarelyMin(2);
Mimosa_afranioi.leaf.bipinnate.pinnae.setNumberOfPairsMinMax(3, 4);
Mimosa_afranioi.leaf.bipinnate.pinnae.rachilla = new Pinnae_1.Rachilla();
Mimosa_afranioi.leaf.bipinnate.pinnae.rachilla.setLength(14);
Mimosa_afranioi.leaf.bipinnate.pinnae.paraphillidia = new Pinnae_1.Paraphillidia();
Mimosa_afranioi.leaf.bipinnate.pinnae.paraphillidia.setLengthMinMax(0.2, 0.5);
Mimosa_afranioi.leaf.bipinnate.pinnae.paraphillidia.shape = ['lanceolate', 'linear-subulate'];
Mimosa_afranioi.leaf.bipinnate.pinnae.paraphillidia.distanceFromFirstPairOfLeaflets = new Paraphillidia_1.DistanceFromFirstPairOfLeaflets();
Mimosa_afranioi.leaf.bipinnate.pinnae.paraphillidia.distanceFromFirstPairOfLeaflets.setLengthMinMax(0.5, 3);
Mimosa_afranioi.leaf.bipinnate.pinnae.paraphillidia.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.leaf.bipinnate.pinnae.paraphillidia.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.leaf.bipinnate.pinnae.paraphillidia.trichomes.filiform.are = 'present or absent';
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet = new Pinnae_1.Leaflet();
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsRarelyMin(4);
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.setNumberOfPairsMinMax(5, 8);
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.setHeightMinMax(2, 7);
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.setWidthMinMax(0.5, 2.5);
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.shape = ['oblong', 'oblanceolate'];
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.base = ['oblique-rounded', 'oblique-subcordate'];
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.apex = ['acute', 'rounded', 'rounded-mucronulate'];
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.abaxial = new Leaflet_1.AbaxialLeaflet();
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.filiform.are = 'absent';
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.granular = new Trichomes_1.Granular();
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.abaxial.trichomes.granular.are = 'present';
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.adaxial = new Leaflet_1.AdaxialLeaflet();
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.adaxial.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.adaxial.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.adaxial.trichomes.filiform.are = 'absent';
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.margin = new Leaflet_1.MarginLeaflet();
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.margin.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.margin.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.leaf.bipinnate.pinnae.leaflet.margin.trichomes.filiform.are = 'absent';
Mimosa_afranioi.inflorescence = new v1_1.Inflorescence();
Mimosa_afranioi.inflorescence.capitate = new Inflorescence_1.CapitateInflorescence();
Mimosa_afranioi.inflorescence.capitate.setLengthMinMax(3.5, 6);
Mimosa_afranioi.inflorescence.capitate.shape = 'globose';
Mimosa_afranioi.inflorescence.shape = 'moriform';
Mimosa_afranioi.inflorescence.peduncle = new Inflorescence_1.Peduncle();
Mimosa_afranioi.inflorescence.peduncle.setLengthMinMax(10, 22);
Mimosa_afranioi.flower = new v1_1.Flower();
Mimosa_afranioi.flower.bracteole = new Flower_1.Bracteole();
Mimosa_afranioi.flower.bracteole.setLengthMinMax(0.5, 1.1);
Mimosa_afranioi.flower.bracteole.shape = 'spatulate';
Mimosa_afranioi.flower.bracteole.apex = new Bracteole_1.ApexBracteole();
Mimosa_afranioi.flower.bracteole.apex.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.flower.bracteole.apex.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.flower.bracteole.apex.trichomes.filiform.are = 'present or absent';
Mimosa_afranioi.flower.merism = '3-merous';
Mimosa_afranioi.flower.calyx = new Flower_1.Calyx();
Mimosa_afranioi.flower.calyx.numSepals = 3;
Mimosa_afranioi.flower.calyx.setLengthMinMax(0.3, 0.6);
Mimosa_afranioi.flower.calyx.shape = 'campanulate';
Mimosa_afranioi.flower.corolla = new Flower_1.Corolla();
Mimosa_afranioi.flower.corolla.numPepals = 3;
Mimosa_afranioi.flower.corolla.setLengthMinMax(1.4, 2.5);
Mimosa_afranioi.flower.corolla.shape = 'campanulate';
Mimosa_afranioi.flower.corolla.lobes = new Corolla_1.Lobes();
Mimosa_afranioi.flower.corolla.lobes.apex = new Lobes_1.ApexLobes();
Mimosa_afranioi.flower.corolla.lobes.apex.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.flower.corolla.lobes.apex.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.flower.corolla.lobes.apex.trichomes.filiform.are = 'present or absent';
Mimosa_afranioi.androecium = new v1_1.Androecium();
Mimosa_afranioi.androecium.filaments = new Androecium_1.Filaments();
Mimosa_afranioi.androecium.filaments.setLengthMinMax(5, 7);
Mimosa_afranioi.androecium.filaments.colour = 'pinkish';
Mimosa_afranioi.androecium.filaments.base = new Filaments_1.baseFilaments();
Mimosa_afranioi.androecium.filaments.base.connation = new baseFilaments_1.ConnationOfFilamentsAtBase();
Mimosa_afranioi.androecium.filaments.base.connation.setLengthMinMax(0.3, 0.4);
Mimosa_afranioi.fruit = new v1_1.Fruit();
Mimosa_afranioi.fruit.type = 'craspedium';
Mimosa_afranioi.fruit.setHeightMinMax(27, 61);
Mimosa_afranioi.fruit.setWidthMinMax(3.5, 8.5);
Mimosa_afranioi.fruit.stipe = new Fruit_1.Stipe();
Mimosa_afranioi.fruit.stipe.setLengthMinMax(2, 5);
Mimosa_afranioi.fruit.shape = 'oblong';
Mimosa_afranioi.fruit.replum = new Fruit_1.Replum();
Mimosa_afranioi.fruit.replum.shape = ['undulate', 'slightly undulate'];
Mimosa_afranioi.fruit.replum.prickles = new v1_1.Prickles();
Mimosa_afranioi.fruit.replum.prickles.are = 'present or absent';
Mimosa_afranioi.fruit.replum.prickles.orientation = ['straight', 'decurved'];
Mimosa_afranioi.fruit.replum.prickles.setLengthMinMax(0.3, 0.5);
Mimosa_afranioi.fruit.replum.prickles.frequency = 'sparsely armed';
Mimosa_afranioi.fruit.replum.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.fruit.replum.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.fruit.replum.trichomes.filiform.are = 'present or absent';
Mimosa_afranioi.fruit.replum.trichomes.granular = new Trichomes_1.Granular();
Mimosa_afranioi.fruit.replum.trichomes.granular.are = 'present or absent';
Mimosa_afranioi.fruit.epicarp = new Fruit_1.Epicarp();
Mimosa_afranioi.fruit.epicarp.prickles = new v1_1.Prickles();
Mimosa_afranioi.fruit.epicarp.prickles.are = 'present or absent';
Mimosa_afranioi.fruit.epicarp.prickles.orientation = 'straight';
Mimosa_afranioi.fruit.epicarp.trichomes = new v1_1.Trichomes();
Mimosa_afranioi.fruit.epicarp.trichomes.filiform = new Trichomes_1.Filiform();
Mimosa_afranioi.fruit.epicarp.trichomes.filiform.are = 'present or absent';
Mimosa_afranioi.fruit.epicarp.trichomes.granular = new Trichomes_1.Granular();
Mimosa_afranioi.fruit.epicarp.trichomes.granular.are = 'present or absent';
// Description authorship
Mimosa_afranioi.descriptionAuthorship = new v1_2.DescriptionAuthorship();
Mimosa_afranioi.descriptionAuthorship.addAuthor({
    name: 'Lucas Sá Barreto Jordão',
    date: 1692107172
});
// Sources
var source1 = new v1_2.Source();
source1.obraPrinceps = 'yes';
source1.sourceType = 'article';
source1.authorship = 'Jordão, L.S.B. and Morim, M.P. and Simon, M.F., Dutra, V.F. and Baumgratz, J.F.A.';
source1.year = 2021;
source1.title = 'New Species of *Mimosa* (Leguminosae) from Brazil';
source1.journal = 'Systematic Botany';
source1.volume = 46;
source1.number = 2;
source1.pages = 339 - 351;
Mimosa_afranioi.addSource(source1);
var source2 = new v1_2.Source();
source2.obraPrinceps = 'yes';
source2.sourceType = 'article';
source2.authorship = 'Jordão, L.S.B. and Morim, M.P. and Simon, M.F., Dutra, V.F. and Baumgratz, J.F.A.';
source2.year = 2021;
source2.title = 'New Species of *Mimosa* (Leguminosae) from Brazil';
source2.journal = 'Systematic Botany';
source2.volume = 46;
source2.number = 2;
source2.pages = 339 - 351;
source2.figure = '2';
source2.obtainingMethod = 'drawing';
Mimosa_afranioi.addSource(source2);
var source3 = new v1_2.Source();
source3.obraPrinceps = 'yes';
source3.sourceType = 'article';
source3.authorship = 'Jordão, L.S.B. and Morim, M.P. and Simon, M.F., Dutra, V.F. and Baumgratz, J.F.A.';
source3.year = 2021;
source3.title = 'New Species of *Mimosa* (Leguminosae) from Brazil';
source3.journal = 'Systematic Botany';
source3.volume = 46;
source3.number = 2;
source3.pages = 339 - 351;
source3.figure = '3';
source3.obtainingMethod = 'photo';
Mimosa_afranioi.addSource(source3);
